### ISSUE TITLE
color-calibration: improve explanation of workflow options and warnings

### ISSUE THREAD

**Issue by matt-maguire** [darktable-org/dtdocs#123]
The description of what the CAT workflow options do is not quite accurate, and doesn't cover the warning introduced in darktable-org/darktable#6836

This topic seems a little unstable, so maybe wait for it to settle down a bit and then update the descriptions.

**Comment by elstoc** [comment]
Agreed

**Comment by elstoc** [comment]
I think this can probably be closed now

**Comment by matt-maguire** [comment]
docs were updated.
