### ISSUE TITLE
Publish dtdocs v3.4 on darktable.org

### ISSUE THREAD

**Issue by elstoc** [darktable-org/dtdocs#134]
v3.4 of dtdocs should be published on darktable.org in time for the release of darktable 3.4 in December

**Comment by paperdigits** [comment]
We want to remove the 2.4 docs from https://www.darktable.org/usermanual/en/ and replace it with the 3.4 docs. I've build and zipped the current 3.4 docs, they can be downloads from my nextcloud: https://cloud.silentumbrella.com/index.php/s/doYJrZncMNTGQj2

**Comment by houz** [comment]
I uploaded the docs.
