### ISSUE TITLE
Black-on-Gray hard to read

### ISSUE THREAD

**Issue by hpdeifel** [darktable-org/dtdocs#139]
I find the current color scheme hard to read because of the low contrast provided by the darkish gray background.

Online contrast checkers seem to disagree with my vision on this one. Also, for having the docs open next to darktable, the color scheme might be ideal.

**Comment by paperdigits** [comment]
Hi I'm sorry this doesn't work for you, but we meet the most stringent contrast standard for accessibility. Eventually the docs will use the canonical darktable.org theme. If neither of those are good for you, you can use the PDF which will be available when 3.4 is released, use a read-it-later service like pocket or the one built into firefox, or inject your own stylesheet using something like greasemonkey.

**Comment by hpdeifel** [comment]
Sure thing, seems I'm the only one...
