### ISSUE TITLE
Auto-build pdf with github-actions

### ISSUE THREAD

**Issue by elstoc** [darktable-org/dtdocs#144]
I'm not sure if the current method of building the pdf will work well with gh-actions.

**Comment by johnny-bit** [comment]
Why not? it's 3 additional steps:
````
pip install weasyprint
```
and then
```
mkdir -p public
hugo server --disableFastRender --config config-pdf.yaml
weasyprint http://localhost:1313/dtdocs/index.html public/darktable_user_manual.pdf
pkill hugo
```
and finally use upload-artifact action to have user manual in artifacts :)

**Comment by elstoc** [comment]
PRs welcome ;-)

**Comment by paperdigits** [comment]
Seems that running hugo server inside the container might be problematic: https://github.com/paperdigits/dtdocs-ci-test/runs/1451339598?check_suite_focus=true

**Comment by paperdigits** [comment]
Never mind, I lied: https://raw.githubusercontent.com/paperdigits/dtdocs-ci-test/gh-pages/darktable_user_manual.pdf

PR incoming.
