### ISSUE TITLE
Use transparent icons

### ISSUE THREAD

**Issue by quovadit** [darktable-org/dtdocs#145]
I would suggest to use **transparent** inline-icons after the text instead of default-dark-background, because:
- it is much clearer to see
- it is independent of themes
- it follows the idea of using images only for explanation but not to illustrate how it looks like in dt

![icons](https://user-images.githubusercontent.com/5677563/99881926-14d35500-2c1d-11eb-9438-cf12bd2b3a53.png)

If there is a decision I will do the job of changing all existing icons.

**Comment by paperdigits** [comment]
How are you planning on changing them? Just editing the current icons and saving a transparent PNG?

**Comment by quovadit** [comment]
just editing the existing icons would be the simplest possibility, but it's quite ugly in my opinion.
So I would try to get vector data out of the cairo_paint code to generate clean pngs.

**Comment by johnny-bit** [comment]
In source we have `tools/show_icons_in_paint_c.pl` which extracts all icons and most of their states to PNG file. It shouldn't be much of a problem to "fix" it or create something very similar to generate transparent icons.
