### ISSUE TITLE
[Workflow] Edit photos with dt, having strong, clipped light source in the frame, like suns set or sunrise

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/dtdocs#161]
Expose to the right (ETTR) should be well known and obeyed, at least most of the time.

However, either as a photographic working style or as the 'nature of the beast' seriously clipped highlights may occur. For example having the sun in the frame of your picture, it is impossible to avoid sensor clipping.

This workflow is not meant to "repair" accidentally blown shots, even the procedure is similar, just in highlight reconstruction you may want to behave differently.

As I often do shoot towards light sources (is this a diction?), here is my workflow, how I deal with it in darktable 3.4 (currently using 3.3.0, the developers version).

I assume you have a little bit more than basic understanding of the methods in darktable, as I do not describe in detail, how to use e.g. contrast equalizer, color balance or filmic in its full technical depth.

**Module highlight reconstruction**

* Typically I switch in this scenario to "reconstruct in LCH"  from the beginning. 
* It might be also helpful to try "reconstruct in color".

In some cases it might even be better to switch of the highlight reconstruction module completely. In that case a more excessive attenuation of scene and reconstruction tab of filmic is needed (not recommended for this workflow)

**Exposure**
* Decide acc. to your taste and the occasion, whether or not you deactivate "compensate camera exposure"
* Avoid to attenuate exposure lower than +0.5EV, definitely not below 0.0EV
* Usually in this case I leave exposure module untouched

**White balance**
At first set your white balance. Ideally neutral, without using it artistically for color casting.

* Either you use the classical module white balance, 
* or you have already switched in preferences/processing/auto-aply chromatic adaptation defaults to modern and use the [new color calibration module](https://discuss.pixls.us/t/introducing-color-calibration-module-formerly-known-as-channel-mixer-rgb/21227)

**Module filmic rgb**

In any case avoid clipping in fimic's graph (orange indicators).

[scene] tab
* Move the slider "white relative exposure" to the right, means increase the values
  * Be careful, not to over cook, as this may wash out your picture
* Adjust black relative exposure to your taste (find your best trade-off)
  * To the left, decreasing the value, preserves the shadows, reduces the (perception of) contrast
  * To the right, increasing the value, provides more (perception of) contrast but losing details in the shadows

[look] tab

Provided you want to have as less desaturation in highlights as possible for your sun set or sun rise, you can try two things acc. to your taste:
* Either use shadows/highlights balance and move it to the left, decrease the value
  * Do not overcook, it can also cause unnatural saturation
or
  * move the latidue to the right, increasing the value or a combination of both

* Contrast slider may be adjusted to taste, I prefer e.g. color balance or other tools as a separate instance

[reconstruct] tab
* Toggle the raw over exposed indicator ![grafik](https://user-images.githubusercontent.com/49004103/100496380-fe188b00-3153-11eb-9234-3d19051136aa.png) e.g. by pressing shift+o (the character, not number)
* Activate the "display highlight reconstruction mask" (picture becomes black
* Pull down the transition slider to the minimum on the left
* Slowly decrease the "Threshold slider (to the left) until the masked area becomes visible, slightly more than your raw over exposed indicator
![grafik](https://user-images.githubusercontent.com/49004103/100496483-aa5a7180-3154-11eb-915c-02610f83ce96.png)
* Reset transition slider (double click on the slider)
* Toggle raw exposure indicator again (shift+o) and unset display highlight reconstruction mask (picture becomes colored again)
* Attenuate transition to your liking (usually +3.0 is quite fine)
(in some cases, this can be too much, e.g. for "golden October sun", in that case reduce the threshold slightly and keep attenuating transition)
* further more, the slider "structure/bloom" can kindo of optimize the results. So attenuate to your liking and be prepared to counter it partially with the [look] tab, as described above.

[options] tab
* You may try to increase the iterations of high-quality reconstruction. 
* Also you may play around with "preserve chrominance" (max RGB might look promising, quite depends on taste and picture)

**tone equalizer**
* Adjust the mask, with mask exposure/contrast compensation, so that the mask-histogram nicely spread between ~-1EV and ~-7EV
![grafik](https://user-images.githubusercontent.com/49004103/100496694-4c2e8e00-3156-11eb-90e2-053bee9f82d4.png)
* Hover your mouse over the light source and gently decrease 
* Increase shadows to your taste

**Final touch**
For the final look and feel, 
* Local contrast, contrast equalizer and color balance can be used.
* At color balance I like to 
  * give a slight touch of orange to the hightlights  and use the color picker for hue in offset (shadows) on something black
* Finally, due to lifting shadows

Here you are...
_____________________
@codingdave and @johnny-bit would you mind, give this a try and kick my ass if it is unclear? If it fails for the result, kick your own ass :-)

@matt-maguire: as discussed on IRC, if this gets your appreciation and no fat complaints from the guinea pigs, would you then merge it to the workfow-section of dt-docs? 

Recommendations for improvements are welcome.

**Comment by codingdave** [comment]
Hi @AxelG-DE,

I worked on a picture of a sundown having a subject in front of it. I don't see any effect of the highlight reconstruction in filmic though.

After repeating my learning for the second time on the same image I got a very different and very pleasing result. I think part of the learning curve is to understand what you can get from a RAW. You somehow need to learn to interpret the input correctly. This is something where I would see a tutorial very helpful, one that covers extreme cases like the sunset you are targeting here. Because I now feel as if I am able to deal with sunset images, but what about non-overexposed scenes? Dark scenes? High-Key, Low-Key?

Anyhow, I have learned and believe others will so too. So thank you for that article!

**Comment by AxelG-DE** [comment]
> I also made use of the reconstruction with bloom

Thanks for the reminder, I updated the article



> I don't see any effect of the highlight reconstruction in filmic though.

still don't or didn't? Snapshot is your friend :-)



> I now feel as if I am able to deal with sunset images, but what about non-overexposed scenes? Dark scenes? High-Key, Low-Key?

An attractive idea!
Indeed @aurelienpierre described also  [extreme cases](https://discuss.pixls.us/t/darktable-3-0-for-dummies-hardcore-edition/15864) and I think we could really think of further extreme case-workflows. 
Did already astro shots with two instances of filmic(upper contrasty, lower compressing the blacks), which are not overlapping indeed. That simulates a bit, that you would have cut your analogue negative film alongside and glued toegether two different types. Good luck to the chem-guy :slightly_smiling_face:  

I do not claim I would be a pro for filmic. Aurélien had to spend lots of tolerance and patience on me and my questions (just hope here and there they also triggered something). Just over the time, I feel quite o.k.-ish with it and get my way around...

**Comment by matt-maguire** [comment]
Highlight reconstruction is only required if there is clipping in the raw file. Otherwise, if there is no clipping, you just need to set the exposure, relative black exposure and the relative white exposure to match the parameters of the scene.

Stacking multiple instances of fimlic is generally a bad idea; remember, filmic applies not only the look transformation, but also a power (gamma) function. By stacking two instances you'll be doubling up on that power function.

**Comment by AxelG-DE** [comment]
> Highlight reconstruction is only required if there is clipping in the raw file.

Which is the initial situation for my aforementioned workflow



> Stacking multiple instances of filmic is generally a bad idea; remember, filmic applies not only the look transformation, but also a power (gamma) function. By stacking two instances you'll be doubling up on that power function.

TBH I am unclear about the consequences of the gamma function and its doubling. As I said above, those two instances did not overlap. I did achieve pleasing results with this approach. Whether or not that could have been done differently, is another story. For astro-photography I am still at the beginning of my experience :)

**Comment by codingdave** [comment]
> I don't see any effect of the highlight reconstruction in filmic though.
    still don't or didn't? Snapshot is your friend :-)
Sure, thats why I turned it on ;-)

    TBH I am unclear about the consequences of the gamma function and its doubling. 
Since filmic converts the linear data (how the sensor received it, power of 2 the light: power of 2 the value) to the log data (how the perception works, power of two the value: double the brightness) it applies the gamma function (e.g. power of 2.2) to the data. If you apply filmic twice then you apply the conversion from linear data to log data twice, meaning the second filmic already works on log data and thinks it is linear data so it logs them again. (As far as I understand it. Might be wrong, though)

**Comment by paperdigits** [comment]
Should we be recommending the use of both the Highlight Reconstruction module and Filmic's highlight reconstruction at the same time?

**Comment by aurelienpierre** [comment]
Highlight reconstruction works well only in its destructive mode (clip highlights). Lch and reconstruct color are very unreliable, especially with XTrans CFA, and can produce patterns.

If you intend on heavily blurring the highlights in filmic reconstruction (blooming effect), it does not matter. But if you want to salvage as much details as possible, it's not the best way. However, filmic reconstruction is more difficult to setup to avoid magenta highlights and many users will stay stuck there, so the usual HL reconstruction is a safer bet.

**Comment by AxelG-DE** [comment]
Perfectly fine with Aurélien's comment.

@paperdigits I understand your worries. However this is not a doc, it just describes, what one dude is doing with the following aims:
* this is merely for that one use case, where you have such an extreme light source in your picture, you cannot avoid clipping
* the sun does not have much structure anyways
* this approach is pleasing to me and fast at the same time (I really struggle with that magenta-ish tone, when using filmic alone)
  * like this it simply works for me
* technically clipping might be more safe. LCH is unpredictable, however, I sit at my controls anyway and can flip between the three HL modes anyways

If you guys want me to rephrase that last sentence in my "Highlight Reconstruction" paragraph, to say that way more clear,  intentionally highlight reconstruction should be done with filmic alone and this workflow is somehow not recommended/intended by the author of filmic, I am fine to do so

**Comment by paperdigits** [comment]
But Axel, these are the docs. We need to emphasize technical correctness and realize that what we write here will be viewed as what the darktable project recommends as a whole.

I don't mean to sound disparaging, as I too have my own things that aren't "the best" way of doing things, but we need to be mindful of the weight of the recommendations that we make here.

**Comment by AxelG-DE** [comment]
> I don't mean to sound disparaging, as I too have my own things that aren't "the best" way of doing things, but we need to be mindful of the weight of the recommendations that we make here.

Happy New Year to you all.

Mica, 
I am totally fine with your comment. (thought I replied in that manner already...)

It is just, having read/seen lots of Aurélilen's posts and videos and also we have had direct communications, I am still struggling to get rid of the magenta cast, when disabling highlight reconstruction module and use filmic stand-alone.

One thing I want to mention: The Aurélien himself seems to use both at the same time https://discuss.pixls.us/t/3-4-scene-referred-workflow-bad-bokeh-highlights-reconstruction/22135/18 :-)

**Comment by kofa73** [comment]
> This workflow is not meant to "repair" accidentally blown shots, even the procedure is similar, just in highlight reconstruction you may want to behave differently.

This sentence reads strange. Since I'm not sure what you were trying to express, and I'm not a native speaker, the following suggestions may be completely off, sorry about that:
- even ?though? the procedure is similar
- in highlight reconstruction you may want to behave differently -> you may want to deal with / treat highlights differently; you may want to apply different highlight reconstruction settings?
