### ISSUE TITLE
Add Windows/macOS file locations to the manual

### ISSUE THREAD

**Issue by Neverest** [darktable-org/dtdocs#171]
In page 15, in the pdf, or in the basic workflow ->editing an image: scene-referred workflow, in the vibrance part it says this:

"vibrance

Tends to darken colors. Consider using using color zones with a saturation parametric mask to give more control."

The word using is repeated there.

Also, I noticed that in the manual it only mentions the location of the local copies, profiles etc of Linux systems. It would be nice if the Windows and macOS file locations where there too.

**Comment by elstoc** [comment]
> The word using is repeated there

Thanks. I'll fix this shortly

> only mentions the location of the local copies, profiles etc of Linux systems

It generally uses variables like `$HOME` to reference the starting portion of the filename. You should replace this $HOME variable with the required path for your OS. Some of these paths are even different between Linux distributions and, certainly for me, I have multiple different installations with different paths defined. Could you point out a specific instance that you think needs to be amended please and why the above formulation doesn't work for other operating systems.

**Comment by Neverest** [comment]
Ok should I start another issue then?

**Comment by elstoc** [comment]
Probably no need now but how about you change the title.

**Comment by Neverest** [comment]
> Could you point out a specific instance that you think needs to be amended please and why the above formulation doesn't work for other operating systems.

Well, in Windows the darktablerc, keyboardrc, library.db and data.db are located in `C:/$USER/AppData/Local/darktable` which by default you first need to go to your File Explorer -> View -> check Hidden Items to be able to see it.

The local copies, log and mipmap files are in `C:\$USER\AppData\Local\Microsoft\Windows\INetCache\darktable` and to be able to see it you need to do the above and go to File Explorer Options -> View tab -> uncheck "Hide protected operating system files".

I mention them because there is a chance the user doesn't know how to make those folders visible, especially the INetCache one. Just yesterday I recommended this program to a friend, that didn't know where the AppData was located, so the less friction from non computer savvy people the better.

For where it would be convenient, in the local copies sections, and the first time the darktablerc file is mentioned. Sorry I can't think of any more areas, since I'm new at Darktable and photography in general.

 It could be a small section called "Configuration File Locations" with a list of all the locations and a brief description of what that file has sort of like[ kdenlive does it](https://userbase.kde.org/Kdenlive/Manual/Installation) but adding the other OS.

**Comment by paperdigits** [comment]
This is covered in the FAQ on the website, and the path for WIndows is `C:\Users\[username]\AppData\Local\darktable\`

**Comment by Neverest** [comment]
Sorry, update got lost in the email influx.

> 
> 
> This is covered in the FAQ on the website, and the path for WIndows is `C:\Users\[username]\AppData\Local\darktable\`

Yeah, but if added in the manual one can check from there, and in my case that I lose internet connection for long periods of time, so I download the pdf, non network reliant.

**Comment by paperdigits** [comment]
Note that if we add this to the manual, we should remove it from the FAQ.
