### ISSUE TITLE
Raw clipping

### ISSUE THREAD

**Issue by kofa73** [darktable-org/dtdocs#181]
https://github.com/darktable-org/dtdocs/blob/master/content/module-reference/utility-modules/darkroom/clipping.md#L23

> The raw overexposed warning indicates where **pixels in the original raw file are clipped** due to physical limitations in the dynamic range of the camera sensor. This module highlights information that was permanently lost at the point of image capture, and you need to deal with it as best you can using highlight recovery techniques.

It is my understanding that in darktable, white balance also contributes to clipping indication (and subsequent clipping if highlight reconstruction is set to do so), even if the original pixels are not clipped.
https://github.com/darktable-org/darktable/issues/4587 and https://github.com/darktable-org/darktable/issues/6596

**Comment by wpferguson** [comment]
Please see the comment I added to https://github.com/darktable-org/darktable/issues/6596.
