### ISSUE TITLE
[Feature request/proposal] Improved 'basic workflow' section

### ISSUE THREAD

**Issue by chucko58** [darktable-org/dtdocs#193]
As I've mentioned [here](https://discuss.pixls.us/t/a-few-n00b-observations-about-darktable-3-4-on-mac/22556), I'm a Lightroom refugee who needs a new platform because LR 6 just doesn't work well in macOS Big Sur. So I am trying to learn darktable and set up a workflow that suits my needs.

I find the [editing an image: scene-referred workflow](https://www.darktable.org/usermanual/en/overview/workflow/edit-scene-referred/) page tries to be a little bit of a tutorial, a little bit of a catalogue of modules, and a little bit of helpful advice, and isn't really good at any of them. It's too long to absorb in a single sitting, and the organization of the page doesn't hold up well under repeated study. 

Further, I've found that the modules DT selects by default - or any of the pipeline presets as shipped, for that matter - don't match up well with the little bit of tutorial.

So, a proposal. I would like to take this one page and break it down into several smaller pages, in the style of a basic operating manual. One idea:

* scene-referred workflow - suggested settings: How to configure DT with reasonable baseline settings for the tutorial.
* scene-referred workflow - basics: This would cover the bare essentials, which IMHO are white balance, exposure, filmic rgb, and crop/rotate. (Or at least that's where I will spend 90% of my time editing photos.)
* scene-referred workflow - polishing images: This might include lens correction, denoise, retouch, sharpen.
* scene-referred workflow - getting the colors you want: Color balance, color correction, graduated filters, etc.
* scene-referred workflow - difficult images and artistic effects: You know, the _fun_ stuff.
* scene-referred workflow - advanced topics: Skim the surface of color profiles, color spaces, etc., with links 

I am willing to write at least the first couple of sections. I am also willing to develop at least a couple of pipeline presets to go along with them:

* essentials - the first two sections above
* intermediate - color & artistic

Sadly I really only know one language, 'Murican English, so I will not be able to help with i18n.

**Comment by paperdigits** [comment]
I agree that the page in question needs to provide the user with action first and explanation  second. It doesn't do that at the moment.

However, the module order should match up well, perhaps you have an old config lying around?

Splitting this content into six pages isn't really feasible. Regardless of length, most users will hit only one page, then leave the site.

**Comment by chucko58** [comment]
It turned out I did in fact have an old config lying around.

I get your point about 6 being too many pages. And having spent a little time with filmic rgb just now, I get the additional point users need to play with things for themselves.

I'll clone the docs and put together a strawman proposal, and a pipeline preset or two to go with it.
