### ISSUE TITLE
Split larger module reference pages

### ISSUE THREAD

**Issue by elstoc** [darktable-org/dtdocs#210]
Some module reference pages are getting quite long, due to the complexity and technical nature of the modules themselves. In order to make for easier consumption it might be better to split them into separate pages with an overview at the start.

The main culprits at the moment are `filmic rgb` and `color calibration`. Here's an initial suggestion as to how they could be split

```
filmic rgb
   overview (prerequisites, usage, graphic display)
   scene tab
   reconstruct tab
   look tab
   display tab
   options tab

color calibration
   overview
   CAT
   channel mixing
   color checker
   caveats
```

@paperdigits, @aurelienpierre, @matt-maguire what do you think?

**Comment by paperdigits** [comment]
I'd much rather add a page ToC than split these up.

**Comment by elstoc** [comment]
> I'd much rather add a page ToC

I've kind of done that in my last copy-edit to color calibration (added some links in the overview section)

**Comment by paperdigits** [comment]
I've put a quick mock-up of the page ToC in the `page-toc` branch of the HTML theme. Let me know what you think, @elstoc

**Comment by elstoc** [comment]
I'm not really a fan of taking more screen real-estate with side panels, especially where they might not be necessary for most pages. IMO it looks a bit crowded even on a 16:9 screen. I'd prefer if it went at the top and was hierarchical, perhaps in a collapsible section?

Could we make the ToC optional on a per-page basis by including a new metadata flag in the header?

**Comment by paperdigits** [comment]
Yes we can make it optional.
