### ISSUE TITLE
filmicrgb 'power function'

### ISSUE THREAD

**Issue by kofa73** [darktable-org/dtdocs#213]
In the description of _target white luminance_ (https://www.darktable.org/usermanual/en/module-reference/processing-modules/filmic-rgb/#display), one can read the following: 'To remove this compression, set the _destination power factor_ to 1.0 and the middle-grey destination to 45%.' However, there is no _destination power factor_ setting in filmic. I think this may be a reference to _hardness (previously target power factor function)_. I may also be worth repeating in the _target white luminance_ section that editing hardness requires that _auto-adjust hardness_ be turned off on the _options_ tab.

**Comment by elstoc** [comment]
Ping @aurelienpierre
