### ISSUE TITLE
improved documentation for demosaic

### ISSUE THREAD

**Issue by elstoc** [darktable-org/dtdocs#218]
There have been a few demosaic-related changes to darktable recently (https://github.com/darktable-org/darktable/pull/7337, https://github.com/darktable-org/darktable/pull/7981) that require documentation. However, it would be nice to also have some more complete documentation for the pre-existing demosaic options, including a guide as to how to choose a demosaic strategy along with pros/cons of the various approaches.

@jenshannoschwalm would you be able to document something to start us off or recommend any resources I could refer to?

**Comment by jenshannoschwalm** [comment]
Yes, i did a lot of work on that :-) I have not been using hugo yet, just installed it and it will take some days to get an understanding of how write docs.

I will go for it.

**Comment by elstoc** [comment]
It's markdown so it's pretty easy. There are a few standards/guidelines we've put together in https://darktable-org.github.io/dtdocs/special-topics/contributing/ but don't worry about that. If you can just write some plain text I'm happy to adjust it as part of my copy-edit. I just don't know enough to know where to start.

**Comment by jenshannoschwalm** [comment]
@elstoc i just read your cleaning up, thanks a lot!

**Comment by elstoc** [comment]
No problem. Thanks for the technical bits :)
