### ISSUE TITLE
noise (profiled): confusing description of "adjust autoset parameters"

### ISSUE THREAD

**Issue by grothesque** [darktable-org/dtdocs#235]
The relevant manual section says:

> In general, the value of this slider indicates the number of stops by which you had to increase the exposure. For example, if you had to push the exposure 2 stops above what you normally use, then set this slider to 2.

This confuses me to the point that I do not understand what this phrase is trying to say.

The default value of this setting is 1.  Taking the example of exposure pushed 2 stops above what one normally uses, I could understand if the slider had to be set to 4 (if its scale is linear), or to 3 (if it's log2).  

But 2?  That's consistent with square-root-of-linear, but if this parameter indeed works this way, the documentation should be more explicit.

**Comment by elstoc** [comment]
Thanks @grothesque. 

@rawfiner please can you advise on this.

**Comment by rawfiner** [comment]
Good point. The message conveyed should be 2^(number of stops added), which gives 1 if no exposure compensation is done

**Comment by grothesque** [comment]
Wow, you guys are responsive...

**Comment by elstoc** [comment]
Thanks @rawfiner - I'll update it

**Comment by elstoc** [comment]
@rawfiner - ok if I change it to

> In general, the value of this slider should be set to the number of stops by which you had to increase the exposure, squared. For example, if you had to push the exposure 2 stops above what you normally use, then set this slider to 4.

**Comment by johnny-bit** [comment]
I wonder if adding another example, eg -1 ev and resulting correction of 0.5 would nail that this is `2^(exposure comp)`

**Comment by matt-maguire** [comment]
Or else we forget about stops and just say that the "effective ISO" used by the denoising algorithm is the actual ISO multiplied by the slider value. The higher the "effective ISO", the more aggressive the denoising parameters will be set.
