### ISSUE TITLE
Image overlays and it's tie to image grouping need some love

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/dtdocs#237]
In a recent conversation on [pixls.us](https://discuss.pixls.us/t/why-dont-i-get-a-g-symbol-on-the-grouphead-thumbnail-of-grouped-images-dt-3-4-1/23912) the OP pointed out that in the documentation there is nothing about having to have permanent overlays turned on in order to expand and collapse individual groups.  Perhaps some images of what the different overlay modes look like and a link from grouping to the overlay that is necessary to take advantage of it.

**Comment by Nilvus** [comment]
@elstoc and @wpferguson: seems that this issue is also fixed with this commit: https://github.com/darktable-org/dtdocs/commit/446cf37cf05056e3e0a063f9796c42da05e8ab5a

**Comment by elstoc** [comment]
Perhaps. This is a broader request though, to also explain the various overlay modes. I'm not sure whether this is needed or not. I'm reluctant to add extra images and probably it's as easy to try it for yourself to see how it looks.
