### ISSUE TITLE
improve handling of luminance estimators

### ISSUE THREAD

**Issue by matt-maguire** [darktable-org/dtdocs#244]
During the discussion on pixls:
https://discuss.pixls.us/t/a-plea-for-more-guidance-in-the-darktable-manual/24118

it became clear that the documerntation concerning luminance estimators could perhaps be better organised in the documentation.

Luminance estimators are used in a variety of modules where the "luminance" of a pixel needs to be estimated for purposes of tone mapping. examples are:
- filmic/filmicrgb
- tone equalizer
- basecurve
- tonecurve
- rgbcurve
- rgblevels

the option may be called various names, such as "luminance estimator", "luiminance", "preserve colours", etc..

It makes sense to factor out the description of possible values into the Darkroom->prosessing_modules>curves section, and reference this section from the various modules using luminance estimators. At the moment, the most comprehensive description of possible values is in the filmicrgb module reference page (which is mainly reflective of the order in which the manual pages were written).

I suggest to pull that information out into the general "curves" page, and in the module reference pages refer back to that description in the curves page.

**Comment by elstoc** [comment]
Should tone equalizer be included here? All of the others are about chrominance preservation but tone equalizer is about guided filters. If they are the same thing but with different usage, how should we treat this in the documentation?

**Comment by elstoc** [comment]
Probably needs @aurelienpierre to weigh in here.

**Comment by aurelienpierre** [comment]
> Chrominance preservation means rather than do tone mapping on color channels separately/individually, you characterise the "luminance" of a pixel by a single value, and then scale all three RGB channels by the same percentage, based on where the luminance estimation falls on the tone mapping curve.

Yup. Which actually falls-back to an exposure compensation by a factor defined with a curve, instead of the flat factor defined in exposure module.

**Comment by elstoc** [comment]
@matt-maguire is that enough information for you to work on a PR? I'm certainly happy for the documentation to be consolidated if it will help.
