### ISSUE TITLE
issues when translating in French

### ISSUE THREAD

**Issue by lebmich** [darktable-org/dtdocs#247]
Some messages that appear to be translated on Weblate website are not translated in my local site http://localhost:1313/dtdocs/fr-fr/
For example:
![2021_04_02_weblate_01](https://user-images.githubusercontent.com/33633321/113388501-9fc41900-938e-11eb-8ba8-01ab92eb3c64.png)
Why ?
Best regards.

**Comment by lebmich** [comment]
I get this on my local site
![2021_04_02_weblate_02](https://user-images.githubusercontent.com/33633321/113389252-fe3dc700-938f-11eb-9428-e871e3747dba.png)

**Comment by paperdigits** [comment]
Hi, its hard to say why, since you've provided no details about what you have done.

**Comment by lebmich** [comment]
You can see what I have done to translate in issue #248

**Comment by lebmich** [comment]
This message appears to have been translated in Weblate website:
![2021_04_04_weblate_01](https://user-images.githubusercontent.com/33633321/113501924-3593ab80-9529-11eb-86ec-8db288713169.png)
However when I import this file from the Weblate site and edit it in emacs it appears as **fuzzy**.
When I remove this flag the message is translated into my html version of the manual.
I think that the character between range and mainly in "high dynamic range images  mainly for data" causes the issue.
I don't know what this character is and how to get it with my keyboard.
Many messages like this one lead to the same issue.

**Comment by paperdigits** [comment]
It looks like a double space to me. Probably a typo that should be removed from the English.

**Comment by elstoc** [comment]
I believe it's a hyphen. Let me try to change it and see what happens

**Comment by paperdigits** [comment]
@elstoc, you will need to regenerate the pot file as well.

**Comment by lebmich** [comment]
In the file **_content.fr-fr.po_** from the Weblate website I now find:
#. type: Plain text
#: content/overview/supported-file-formats.md
#, fuzzy, no-wrap
#| msgid " ...high dynamic range images  mainly for data exchange between darktable and other software.\n"
msgid "...high dynamic range images -- mainly for data exchange between darktable and other software.\n"
msgstr "...grande plage dynamique -- principalement pour des échanges de données avec d’autres logiciels.\n"

In the file **_content.po_** I now find:
#. type: Plain text
#: content/overview/supported-file-formats.md
#, markdown-text, no-wrap
msgid "... dynamic range images -- mainly for data exchange between darktable and other software.\n"
msgstr ""

The message is still not translated.

**Comment by lebmich** [comment]
In the Weblate web we still have:
![2021_04_05_weblate_01](https://user-images.githubusercontent.com/33633321/113548416-cb920980-95ef-11eb-8fca-b840f21ab3ef.png)
 with the hyphen unchanged in the English message.

In the file _supported-file-formats.md_ we have this message:
<<darktable supports a huge number of file formats from various camera manufacturers. In addition darktable can read specific low dynamic range and high dynamic range images -- mainly for data exchange between darktable and other software.>>
with the hyphen changed.

This message is always untranslated.

**Comment by lebmich** [comment]
We also have several other inconsistencies. For example:

In Weblate website

You can give an image a rating from zero to five stars. The quality criteria which lead to a rating are up to you. Whenever you import images, each image receives a default rating which you can define in [preferences > import](../../../preferences-settings/import.md).  _You can also mark an image as **rejected.**_

In the file _star-color.md_

You can give an image a rating from zero to five stars. The quality criteria which lead to a rating are up to you. Whenever you import images, each image receives a default rating which you can define in [preferences > import](../../../preferences-settings/import.md). _You can also mark an image as **“rejected”**_.

and this message is untranslated.

**Comment by lebmich** [comment]
Here is another inconsistencies:
In file _content.pot_ we find:
msgid "... This includes modifications to color labels, ratings, geo-localization, tags, metadata, orientation, copy/paste of history, **image duplication**, or application of a style...."

In Weblate website we find:

This includes modifications to color labels, ratings, geo-localization, tags, metadata, orientation, copy/paste of history, or application of a style.
without **image duplication**

and the corresponding message is not translated.

**Comment by paperdigits** [comment]
Yes there have been several changes, the POT file needs to be regenerated. I'm working on automating that.

**Comment by lebmich** [comment]
Many thanks !

**Comment by paperdigits** [comment]
I'm still not sure what is causing the issue, I'm continuing to investigate this.

**Comment by paperdigits** [comment]
@lebmich I've updated the POT and PO files, can you please check now?
