### ISSUE TITLE
issue when generate-translations.sh runs 

### ISSUE THREAD

**Issue by lebmich** [darktable-org/dtdocs#248]
To translate the manual into French I proceed as follows:
1. run generate-translations.sh  --rm-translations
2. run generate-translations.sh  --no-translations
3. run generate-translations.sh  --no-update
4. translate some messages in French on the Weblate website and import the content.fr-fr.po file in my fork of dtdocs
5. run generate-translations.sh  --no-update
6. repeat items 4 and 5 several times
As results I can get this
 content/special-topics/opencl/_index.fr-fr.fr-fr.fr-fr.fr-fr.fr-fr.fr-fr.fr-fr.md is 100% translated (1 strings).
I think this is due to the following test in the file generate-translations.sh
    $(find content -type f -name '*.md')
which selects the file _index.fr-fr.md and so on...

**Comment by paperdigits** [comment]
I will take a look this weekend, thanks.

**Comment by lebmich** [comment]
Your suggestion corrects the problem.
But when we run `generate-translations.sh --rm-translations` we get in the output:
updating po/content.po
updating po/content.fr-fr.po
...
II think these two commands are not necessary in my use and they consume a lot of time.
To save time I run the following script from the directory tools:
`cd ../content && find . -name "*.fr-fr.md"|xargs rm -f && cd ../tools && ./generate-translations.sh --no-update`
This run fine for me (translating in French).

Furthermore, to be able to see the translations even when less than 80% are done in a section, I set the keep parameter to 0 in the options of the `generate-translations.sh` script (opt:"--keep=0").

**Comment by paperdigits** [comment]
> II think these two commands are not necessary in my use and they consume a lot of time.

PO4A does this by default. I'm not sure how to make them not run while still using PO4A.
