### ISSUE TITLE
Synchronization between markdown files and content.pot file

### ISSUE THREAD

**Issue by lebmich** [darktable-org/dtdocs#253]
Can you please sync the markdown files and the content.po file? I spent all this Saturday afternoon translating content.po messages on the Weblate website. I just noticed that they are no longer present in the markdown files: files relating to the masking&merging section. It's discouraging.

**Comment by elstoc** [comment]
@paperdigits I'm not sure how to do this. I know you're looking at automating this in the CI at some point but if you could just run it once and commit for now that'd be great. Thanks.

**Comment by paperdigits** [comment]
Yes I will do this shortly.

On April 17, 2021 12:55:55 PM PDT, Chris Elston ***@***.***> wrote:
***@***.*** I'm not sure how to do this. I know you're looking at

**Comment by paperdigits** [comment]
POT file update in 78b8982cfb5ca0f3689eb058732065b405d6a9ee
