### ISSUE TITLE
Some more information about the demosaicers available

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/dtdocs#257]
I have looked for examples to show differences in demosaicers output and could provide these as examples.
The scene is zoomed in, no lens correction  at a beach in summer with sunny reflections on the water surface (so some photosites out of range), so a pretty common scenario.
![area](https://user-images.githubusercontent.com/50982232/115612430-89eda800-a2eb-11eb-9276-b598c0ba3dd7.png)

I would like to point out at two areas with visible differences. For the green area you will find heavy overshoots for PPG. AMaZE and RCD keep stable without such overshoots, such issues would also often be present on sun shining on green leaves or grass. VNG is a bit more blurry and tends to create blocks.

In the red area with less details there is not much difference betweeh PPG, AMaZE and RCD, for VNG you can observe a slight shift of colors.
Please let me know whether this would be a desired addition for the manual ...

PPG
![PPG](https://user-images.githubusercontent.com/50982232/115624325-c2e14900-a2fa-11eb-95d5-09dd943776a5.png)

AMaZE
![AMaZE](https://user-images.githubusercontent.com/50982232/115624338-c70d6680-a2fa-11eb-8c7d-67e016d84d39.png)

RCD
![RCD](https://user-images.githubusercontent.com/50982232/115624349-cbd21a80-a2fa-11eb-8355-ba6b50167436.png)

VNG
![VNG4](https://user-images.githubusercontent.com/50982232/115624355-cd034780-a2fa-11eb-88a9-c8d2f43d2b08.png)

**Comment by elstoc** [comment]
I think it's probably useful to have but needs some smaller pictures so that 'side-by-side' comparison is easier - it's hard to assess when you have to scroll between the images. Unless we can make it really compact I'm not 100% sure it should go in the module documentation itself. Perhaps we can link to an Appendix or something.
