### ISSUE TITLE
Suggested edit to documentation

### ISSUE THREAD

**Issue by brucewilliamsphotography** [darktable-org/dtdocs#258]
This relates to this page here:
https://darktable-org.github.io/dtdocs/special-topics/color-management/color-dimensions/?fbclid=IwAR0wAtrYz0Eqf_I07Mk6A7CUm5CZiT_H0aKRqtnhzXrflWjenIfc02vPcoo

"These two frameworks provide us with metrics and dimensions to analyze color and allow us to change some of its properties while preserving others unchanged."

This sentence is badly-formed in English. "Preserving others unchanged" is redundant.
The sentence should either have the word "unchanged" dropped from the end, or the word "preserving" should be changed to "keeping".

**Comment by elstoc** [comment]
I agree. Let's just lose the word "unchanged".
