### ISSUE TITLE
Messages not found on Weblate website

### ISSUE THREAD

**Issue by lebmich** [darktable-org/dtdocs#260]
When translating into French on the Weblate site the _Rechercher_ tab does not find several messages which are present in the _content.pot_ and _content.fr_fr.po_ files. For example "you can define three control patches" in the file "color-balance.md" or "darktable is an open source photography", etc ... Note that these messages are found on the Weblate site when translating into German .

**Comment by lebmich** [comment]
Any idea ? Such messages cannot be translated in French ! Since they are not visible.

**Comment by paperdigits** [comment]
Hi I just updated the POT and PO files. I see the mentioned in the French po file.

Just for note, the POT file is updated manually by me, so it many not match what is written in English on the github pages site.

If you'd like me to update the POT and PO files, please just ping me in IRC or on the pixls.us forum and I'll do it.
