### ISSUE TITLE
add explaination to color mapping module control

### ISSUE THREAD

**Issue by sjjh** [darktable-org/dtdocs#283]
_Relevant file:_ https://github.com/darktable-org/dtdocs/blob/259a86bf72e40c329de283ab50c37db0236c3d33/content/module-reference/processing-modules/color-mapping.md
_Relevant section:_ number of clusters : The number of color clusters to use. If you change this parameter all collected color clusters are reset and must be re-acquired.

Reading the documentation, it's good to learn what effects changing the control has. But honestly by reading the section I have no clue about what the control actually does. What does a change do to the module functionality? I believe it would be good to add a sentence like "Increase the number of color clusters to _achieve A_ or decrease the number to _achieve B_." to add value to the documentation.

**Comment by elstoc** [comment]
Unfortunately the documentation is currently just copied+pasted from the previous version and I've never used this module. I'd welcome any improvements if someone knows how it works.

**Comment by matt-maguire** [comment]
The number of clusters really depends on the characteristics of the image you are dealing with. If your image has 3 dominant colours (eg. blue sky, green grass, white mountains) then 3 clusters is what you are going for. If you have a more complex image, then you might need more clusters. However, the clusters are aquired through random sampling, and as you add more clusters in a complex image, there is bigger chance that the clusters picked out through chance are not appropriate. In the original paper on which this modle was based, the authors would pick out manually swatches around which to base the clusers, and so could they could make some intelligent choices. When you roll the dice, however, you will get something that is not repeatable.

For this reason, I would not recommend to use this module.

**Comment by matt-maguire** [comment]
Original paper is here, is case you're interested:
https://doi.org/10.1109/38.946629

**Comment by sjjh** [comment]
Thanks for the explanation. I'll try to formulate a short sentence for the documentation with this information.
