### ISSUE TITLE
provide context for search results

### ISSUE THREAD

**Issue by elstoc** [darktable-org/dtdocs#297]
When searching the online manual, all that appears is a list of page titles. If the word you're searching for is part of a page title then that works fine, but if the word appears in the page content it's virtually impossible to know which entry to click on unless you know exactly where to find things in the UI. As an example, if you want to know how to remove an image from darktable and you type "remove" into the search box, the actual entry you need (selected images) appears over half way through the results.

This could be made a little less hit-and-miss by taking the user to a results page and highlighting the search term in context.

I have no idea how to do this.

**Comment by alenaksu** [comment]
Hi @elstoc, I opened a PR that should fix this, please take a look

**Comment by paperdigits** [comment]
@alenaksu thank you so much!
