### ISSUE TITLE
colorbalancergb contrast usage note

### ISSUE THREAD

**Issue by kofa73** [darktable-org/dtdocs#298]
Incorporate https://discuss.pixls.us/t/rebooting-color-balance/21888/280 into the documentation, in more refined language :-)

**Comment by kofa73** [comment]
Where should this go?
One option is a separate usage note on contrast, comparing the options (filmic, tone EQ, cb-rgb). The other possibility would be with cb-rgb, most probably (though it is my understanding that the same logic regarding masking and the ability to alter the fulcrum applies to tone EQ just as well). Perhaps a chapter called titled 'Usage notes' or 'Tips and tricks' would be useful to cover topics that are not covered by a single module.

**Comment by matt-maguire** [comment]
I'd put a caveat in the description of cb rgb contrast control that it can affect white/black points, that it is best used for adjustments to a masked region, and suggest to look as tone equaliser for global tonemapping adjustments, and in tone equaliser clarify why it is recommended for the endpoins of the curve to be zero.

**Comment by kofa73** [comment]
Actually, it's already there: https://www.darktable.org/usermanual/3.6/en/module-reference/processing-modules/color-balance-rgb/#master-tab

> The contrast algorithm ... will also increase the image’s dynamic range, which may void filmic settings in the pipe. For global contrast adjustments, you should normally use the tone equalizer module – the color balance RGB contrast slider is best used with masks, e.g. for selective corrections over the foreground or background.
