### ISSUE TITLE
3.6 user manual - color checker white patch as "20% reflective"?

### ISSUE THREAD

**Issue by ellelstone** [darktable-org/dtdocs#338]
darktable 3.6 user manual: https://www.darktable.org/usermanual/3.6/en/special-topics/color-pipeline/

says this:

display-referred
Pixel values are expected to lie between 0 and 100% of the display range, where 100% is understood to be the luminance of a 20% reflective white surface (the white patch of a Color Checker) and 0% is understood to be the maximum density of the output medium (saturated black ink or minimum LED panel backlighting).

The value "20% reflective" for the Color Checker white patch seems very low - how is "reflective" defined here?

The reflectance (https://en.wikipedia.org/wiki/Reflectance) of white paper can reach 90%.

https://chromaxion.com/information/ColorChecker_Passport_Technical_Report.pdf says the reflectance of the white balance chart (which is roughly the same as neutral patch 8, so gray rather than "white") is about 60%.

So I was curious whether the "20%" value is a typo, or whether "reflective" as used in the darktable manual means something other than "reflectance".

**Comment by elstoc** [comment]
Hmm I think this came from @aurelienpierre, perhaps he can confirm.

**Comment by matt-maguire** [comment]
I doubt it -- Aurélien authored that man page, so he wouldn't be questioning himself. On the other hand, it does seem like the type of question someone like Elle would ask.

**Comment by matt-maguire** [comment]
Sorry Chris -- I think you meant the manual page came from Aurélien, not the PR :-)

I agree that 20% is too low -- normally that would correspond to the reflectance of a grey card, which would normally correspond to middle-grey in the display colourspace at around 50%. So, I think @aurelienpierre should review this and correct it.
