### ISSUE TITLE
Unbreak input profile - 'logarithmic' undocumented

### ISSUE THREAD

**Issue by kofa73** [darktable-org/dtdocs#343]
`unbreak-input-profile.md` only documents the _gamma_ method, not _logarithmic_.
A step-by-step guide explaining the sliders and pickers is here: https://discuss.pixls.us/t/solving-dynamic-range-problems-in-a-linear-way/9006/63
It may be mentioning the relationship with _filmic_, as described in the following comment: https://discuss.pixls.us/t/log-tone-mapping-solved/16812/6

**Comment by elstoc** [comment]
@aurelienpierre please can you look at this since iirc this is your change
