### ISSUE TITLE
Render every language into its own folder, including English/The epub build is broken

### ISSUE THREAD

**Issue by paperdigits** [darktable-org/dtdocs#345]
@elstoc mentioned we should render English into its own subdirectory, e.g. en-us, fr-fr, etc etc.

Is this the only way to do this in Hugo? https://gohugo.io/content-management/multilingual/#configure-multilingual-multihost

**Comment by paperdigits** [comment]
Doing this should also allow us to package the epub relatively easily, no?

**Comment by paperdigits** [comment]
During the epub build, in the currently failed action, hugo is putting each language in its own folder, including English. I'm not sure when it started doing that.

**Comment by elstoc** [comment]
@paperdigits: for now, for the darktable.org builds of dtdocs we need to build epub and pdf documents without translations. The CI already does this so I would suggest running the same code that the CI does when building.

**Comment by paperdigits** [comment]
@elstoc what did you do to fix the CI?

**Comment by paperdigits** [comment]
The search is also broken for non-English languages. The correct index.json is created in each language, but we've hard-coded the URL and it points to the English index.json file.

Right now in `app.js` we have the following:

```
// Initialize lunrjs using our generated index file
function initLunr() {
    var request = new XMLHttpRequest();
    request.open('GET', '{{ "index.json" | absURL }}', true);
```

**Comment by elstoc** [comment]
I fixed this yesterday and it now works on gh pages

**Comment by paperdigits** [comment]
I think for the epub, we'll just need to copy all the images into place after we build the HTML.

Something like this should work:
```
find /source -regextype posix-extended -regex '.*(gif|jpg)' \
    -exec cp --parents {} /dest \; -print
```

**Comment by paperdigits** [comment]
This works, it just needs to be looped:

`cd content && find ./ -regextype posix-extended -regex '.*(gif|jpg|png|svg)'     -exec cp --parents {} ../public-epub/de \; -print`

**Comment by elstoc** [comment]
This is done now
