### ISSUE TITLE
Portuguese menu-items in english version

### ISSUE THREAD

**Issue by quovadit** [darktable-org/dtdocs#366]
The english version of dtdocs 3.7 shows some portuguese  menu-items

https://darktable-org.github.io/dtdocs/en/lighttable/
![image](https://user-images.githubusercontent.com/5677563/140979151-69ffd6fc-3e48-434b-b6d8-f2658a45e28c.png)

It seems that all portuguese pages without english translation are shown.

In contrast: the german / french / ... versions correctly only show native articles, no portuguese items.

**Comment by elstoc** [comment]
Thanks. We think it might be differing case between the config and po files. @paperdigits is going to take a look later on.

**Comment by paperdigits** [comment]
Hi, we are aware of the problem and are working on a fix, thanks.

**Comment by elstoc** [comment]
Looks to be fixed following the latest translation update
