### ISSUE TITLE
[FR] Literal search using "quotes"

### ISSUE THREAD

**Issue by quovadit** [darktable-org/dtdocs#367]
The search function of dtdocs works great in most cases.

But in  order to find specific terms it would be very useful to use "quotes" for a literal search.

Searching for "per metadata settings" currently shows articles with only one of the three search-terms, but it does not show the article with a heading "per metadata settings":  https://docs.darktable.org/usermanual/3.6/module-reference/utility-modules/shared/export/#per-metadata-settings

**Comment by paperdigits** [comment]
Hi, you need to use the right search operators in order to do this. To make a term requisite to your search, use a + symbol in front of it: +per +metadata

See the search library documentation for more info: https://lunrjs.com/guides/searching.html

**Comment by quovadit** [comment]
thanks for the quick reply.

Using +per +metadata +settings does show the wanted page on position 5

But the first 4 search results do NOT include all 3 search terms

**Comment by paperdigits** [comment]
I am not JavaScript expert and I welcome enhancements to any part of our website or docs :)
