### ISSUE TITLE
Broken links to current stable and master docs

### ISSUE THREAD

**Issue by elho** [darktable-org/dtdocs#369]
`README.md` uses https://www.darktable.org/usermanual/en as link to current stable docs, which 404s.

I did not find a working alternative for these, but trying to do so, I also noticed that https://docs.darktable.org/usermanual/master/en/ leads to an infinite redirect (via refresh) loop.

**Comment by elstoc** [comment]
We are aware of multiple issues around redirects on docs.darktable.org and are currently investigating.

**Comment by elstoc** [comment]
README link and infinite redirect both now fixed.
