### ISSUE TITLE
New formulation

### ISSUE THREAD

**Issue by lebmich** [darktable-org/dtdocs#374]
The following sentence

Thumbnails are created when an image is imported into darktable for the first time, after an image has been modified in the darkroom, or when revisiting an image whose thumbnail is no longer available.

could not be replaced by
 
A thumbnail is created when an image is imported into darktable for the first time, after an image has been modified in the darkroom, or when revisiting an image whose thumbnail is no longer available.
?

**Comment by elstoc** [comment]
Why not. 

FYI for simple stuff like that you can edit the file directly in github and submit a Pull Request.
