### ISSUE TITLE
Example images in docs?

### ISSUE THREAD

**Issue by will-ca** [darktable-org/dtdocs#383]
https://github.com/darktable-org/darktable/issues/10438

> **Which new feature or section need to be documented/updated**
> 
> 
> What appear to now be obsolete versions of the documentation had a lot of example images in it:
> 
> https://darktable.gitlab.io/doc/en/modules.html
> 
> https://web.archive.org/web/20200111220403/https://www.darktable.org/usermanual/en/color_group.html
> 
> https://web.archive.org/web/20201111200853/https://www.darktable.org/usermanual/en/correction_group.html
> 
> https://web.archive.org/web/20201123144148/https://www.darktable.org/usermanual/en/module_groups.html
> 
> https://web.archive.org/web/20201111193625/https://www.darktable.org/usermanual/en/tone_group.html
> 
> https://web.archive.org/web/20200509201527/https://www.darktable.org/usermanual/en/effect_group.html
> 
> I personally found these really useful. It made it easier to scan through the docs to find which modules might give the effects I wanted, and when the module in question had non-obvious behaviour, it made it easier to understand what was going on.
> 
> Is there any chance of bringing these back? It looks like all the work to create and write captions for the examples has already been done anyway; It would be a shame to lose this resource.
> 
> ![image](https://user-images.githubusercontent.com/37680486/142572410-7e7b697a-712f-47b4-a719-a3639e9b8bdf.png)
> 
> ![image](https://user-images.githubusercontent.com/37680486/142572461-146b47e1-5623-4d92-9f13-2a3f3b70feb9.png)
> 
> ![image](https://user-images.githubusercontent.com/37680486/142572531-fe6fab85-839d-4428-85dc-43207620ff15.png)

**Comment by will-ca** [comment]
> This is a conscious (and much-debated) decision to reduce the amount of maintenance required and to improve the experience for translated manuals - since any images with text in them (screenshots of the modules) cannot be translated. The manual assumes that the user has darktable open in front of them (so can already see the module layout). Also, a lot of the images and examples were against modules that are no longer recommended and including the images was more likely to direct people to those modules.
> 
> We believe that we have included images in the new manual where they add to comprehension but are open to discussion if you want to argue for the usefulness of a particular set of guides. We will still very much err on the side of no images where practical, so a general "please put all the images back" discussion will likely go nowhere.
> 
> Either way this is not the correct repository for issues with the user manual - you need to raise an issue against the [dtdocs repo](https://github.com/darktable-org/dtdocs/issues)

_Originally posted by @elstoc in https://github.com/darktable-org/darktable/issues/10438#issuecomment-973841889_

**Comment by will-ca** [comment]
IMO the translation problem seems like it'd apply only to the example images that are already least useful. I basically agree that screenshots of the GUI are of limited point, especially since the user probably has Darktable open right in front of them.

But I personally found examples of the *effects* of the modules to be quite helpful, since they save the time of having to experiment with different settings yourself. And when including the UI does make sense, it's usually because of elements that are graphical in nature (sliders, curves, etc.) and thus don't really benefit from being translated either. IMO there's rarely much point to screenshots of GUIs, but I found that being able to see examples of what each module actually does to an image was way clearer than parsing the text and much faster than experimenting myself. And as long as the example photos get the basic point across (I.E. there's no fundamental changes in the behaviour of the module), it doesn't really seem to me like they'd add all that much of an ongoing maintenance burden either.

**Comment by paperdigits** [comment]
> And as long as the example photos get the basic point across (I.E. there's no fundamental changes in the behaviour of the module), it doesn't really seem to me like they'd add all that much of an ongoing maintenance burden either.

I don't agree with this at all. The new scene referred modules all have several iterations in thr last several versions that have changed/added options to the module. 

For example in filmic, you can choose your color science version and also enable/disable the mid gray slider. Are we going to catalog all of them? It'd be probably 30 pages of example images.

Also the point is for the user to experiment and learn the modules, how far you can push them, what they do at the extremes, etc etc.
