### ISSUE TITLE
Broken link to manual in PDF

### ISSUE THREAD

**Issue by agarciamontoro** [darktable-org/dtdocs#396]
In https://docs.darktable.org/usermanual/3.6/, the link to the PDF in the phrase "You can also click on the following links to download the manual in PDF or epub format." is broken.

The link points to https://docs.darktable.org/usermanual/3.6/darktable_user_manual.pdf, where I get a 404 Not Found

![image](https://user-images.githubusercontent.com/3924815/144140357-10ca6edf-6887-4000-86f5-9f13387752d6.png)

**Comment by elstoc** [comment]
The link to the pdf file in the 3.6 user manual seems to work correctly now
