### ISSUE TITLE
channel mixer module

### ISSUE THREAD

**Issue by lebmich** [darktable-org/dtdocs#402]
The deprecated module _channel mixer_ is no longer in version darktable 3.8. However it is still documented in manual 3.8.
Could we not remove it from the manual?

**Comment by elstoc** [comment]
It's still useable on old images and there's an open debate about whether or not we should continue to include documentation for deprecated (removed) modules for that reason. Either way, we're not making any more changes to the EN version of the manual now until after darktable 3.8 is released.

**Comment by paperdigits** [comment]
I feel that if we can still get to that module, we should have docs for it. Depreciated modules aren't changing, so its not like they need updates/changes.

One can also make a style with the depreciated module to keep using it.
