### ISSUE TITLE
Translation assistance required (Finnish to English)

### ISSUE THREAD

**Issue by Graycard** [darktable-org/dtdocs#404]
In looking at the new manual for darktable 3.8 (English), there is still a bit of Finnish-language text that needs to be translated to English in Section 1, pages 6 and 7.  Thanks for all the good work, in any case.

**Comment by elstoc** [comment]
You're saying we have Finnish-language text in the English version of the user manual? I don't understand.

**Comment by elstoc** [comment]
Never mind I see it now https://darktable-org.github.io/dtdocs/en/overview/

**Comment by elstoc** [comment]
Should be fixed now

**Comment by Graycard** [comment]
Thank you!

**Comment by Graycard** [comment]
It's fixed.  Thanks again!
