### ISSUE TITLE
Grouping docs: mention that overlays need to be enabled to see grouping icon

### ISSUE THREAD

**Issue by inducer** [darktable-org/dtdocs#406]
I just spent a fair while trying to figure out how to follow the instructions in the [grouping docs](https://docs.darktable.org/usermanual/3.8/en/lighttable/digital-asset-management/grouping/):

> You can define which image is considered to be the group leader by clicking on the group icon of the desired image while that group is expanded.

I think this should also mention that, in order to show the grouping icon on the image, it is necessary to enable "permanent picture infos" (sorry, translating from German here) in the "star" menu. I was very confused because the grouping icon, which the docs said should be there, was not in fact shown.

**Comment by inducer** [comment]
Though, perhaps, as usability issues go, I think it might be better if the grouping icon on an image were always shown if it is part of a group... IMO there's not much of a reason not to. In fact, I think the grouping feature isn't really usable without that icon.

**Comment by elstoc** [comment]
> Though, perhaps, as usability issues go, I think it might be better if the grouping icon on an image were always shown if it is part of a group

You'll have to raise that one on the darktable repo. We're not making string changes to the manual for the next month so I'll tag this for 4.0 and revisit later.

**Comment by dutchieit** [comment]
As a new Darktable user this was sooo frustrating for me to figure out.  In hindsight it's pretty simple, but who would have guessed that the "star" icon didn't control the star ratings, it controls the thumbnail overlays!
Why wait for 4.0?  Please just update the documentation on grouping.  All you need to do is add this:

Note: To see the group icon on thumbnails, make sure that the "permanent overlays" are enabled in the thumbnail overlays menu.  See: "thumbnail overlays" in the "[Top Panel](https://docs.darktable.org/usermanual/3.8/en/overview/user-interface/top-panel/)".

**Comment by elstoc** [comment]
The documentation for 3.8 is frozen and will not be updated further.

**Comment by Nilvus** [comment]
@elstoc: seems that this issue could be closed as you fix it with few days ago with https://github.com/darktable-org/dtdocs/commit/446cf37cf05056e3e0a063f9796c42da05e8ab5a

**Comment by elstoc** [comment]
Indeed. Thanks!
