### ISSUE TITLE
Contradictory advice in diffuse or sharpen module

### ISSUE THREAD

**Issue by mbaz** [darktable-org/dtdocs#412]
The Diffuse or Sharpen module docs (https://docs.darktable.org/usermanual/3.8/en/module-reference/processing-modules/diffuse/) has the following advice in different paragraphs:

* Introduction: undo effect of anti-alias filter with a preset and by placing the module before input color profile (that is, fairly early in the pipe).
* [General advice](https://docs.darktable.org/usermanual/3.8/en/module-reference/processing-modules/diffuse/#general-advice): D or S should come after chromatic aberration, noise correction, black level correction and color calibration.
* [Using multiple instances for image reconstruction](https://docs.darktable.org/usermanual/3.8/en/module-reference/processing-modules/diffuse/#using-multiple-instances-for-image-reconstruction): suggests an order placing sensor and demosaic correction as the last D or S instance.

I think the manual could be improved by placing all discussion about module ordering in a single section, providing one suggested order, and maybe discussing when and why to deviate from it.

Previous discussion: https://discuss.pixls.us/t/recover-ooc-jpeg-detail-sharpness-from-raw-with-darktable/28911/56

**Comment by elstoc** [comment]
@aurelienpierre can I have your input here please?

**Comment by kanyck** [comment]
That concerns me, too. Guidelines are contradictory.
