### ISSUE TITLE
Recommend build instruction update due to new Github protocol

### ISSUE THREAD

**Issue by Dave22152** [darktable-org/dtdocs#440]
It appears that Github changed their protocol and the git clone command `git clone git://github.com/darktable-org/darktable.git` is no longer supported.  The recommended alternative `git clone https://github.com/darktable-org/darktable.git` will initiate the operation.  The rest of the build procedure is unaffected.  I wanted to suggest updating the darktable build instructions to avoid future confusion.

More information on the change to protocol can be found at [ https://github.blog/2021-09-01-improving-git-protocol-security-github/](https://github.blog/2021-09-01-improving-git-protocol-security-github/)

**Comment by elstoc** [comment]
You mention the "darktable build instructions" but these are not part of dtdocs. Please could you clarify exactly what you think needs updating?

**Comment by Dave22152** [comment]
I was referring to the build instructions on https://github.com/darktable-org/darktable/blob/master/packaging/windows/BUILD.md

**Comment by elstoc** [comment]
Indeed. Please raise an issue [here](https://github.com/darktable-org/darktable/issues/new/choose) or a pull request.
