### ISSUE TITLE
Fuji X-S10

### ISSUE THREAD

**Issue by Barbara3065** [darktable-org/dtdocs#452]
Hi
I get the following error when I try to connect with my camera to download my pictures: 
<img width="579" alt="Fuji_Darktable" src="https://user-images.githubusercontent.com/104193145/164689663-2956c980-37d4-4ecc-a593-f5ba5e03eb4a.PNG">

Thanks for your help
Barbara

**Comment by elstoc** [comment]
The dtdocs repository is for issues with the documentation. Please report issues with the darktable application [here](https://github.com/darktable-org/darktable/issues/new/choose)
