### ISSUE TITLE
Minor rewording if snapshots modules

### ISSUE THREAD

**Issue by nhrdl** [darktable-org/dtdocs#474]
https://github.com/darktable-org/dtdocs/blob/master/content/module-reference/utility-modules/darkroom/snapshots.md

Snapshot module documentation does mention only about splitting snapshot about vertical and horizontal modes. Please add a small snippet that this feature allows you to flip snapshot and current view from left to right or bottom to top or vice a versa.

Very small change, hence not creating pull request.

**Comment by elstoc** [comment]
It says "If you hover over the splitline with your mouse, a small rotation icon will appear on the center of the line. Click this icon to change between vertical and horizontal split view."

What is it you want to change?

**Comment by nhrdl** [comment]
The wording does not mention that snapshot image and current image can be flipped by every click. I discovered it accidentally. There are legitimate needs to flip snapshot and current image from left to right or vice a versa.

Functionality is there, just needs to be documented
