### ISSUE TITLE
Wrongly documented -d parameters

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/dtdocs#491]
1. `--enforce-tiling` is not implemented any longer, it did not work as intended
2. `-d verbose` for some options (like opencl `-d opencl`) that might be **followed** by `-d verbose` to give even more output. Please not that `-d all` does not switch it on automatically but also requires a following `-d verbose`
3. we now have `-d tiling` telling what happens there

**Comment by elstoc** [comment]
I've attempted to clarify this in https://github.com/darktable-org/dtdocs/commit/c86f80ed15cb0e6298bf1b1b75c6b2f7fb356327. Please close if this resolves the issue for you.

**Comment by jenshannoschwalm** [comment]
No completely, the verbose switch is not specific for a subsystem but global.

I forgot to implement what you described so I suggest to keep your docs and correct functionality.

**Comment by elstoc** [comment]
> I forgot to implement what you described so I suggest to keep your docs and correct functionality.

Only if you think it will be implemented for 4.0, otherwise I'd prefer the docs to describe how it works.

**Comment by elstoc** [comment]
I've put the documentation of the verbose option back to the previous wording for now.

**Comment by jenshannoschwalm** [comment]
Looks ok

**Comment by elstoc** [comment]
I'll close this for now. If you change the behaviour in darktable, it'll get tagged and the documentation updated.
