### ISSUE TITLE
Duplicate manager preview very small after using crop

### ISSUE THREAD

**Issue by BeagleDad** [darktable-org/dtdocs#510]
<img width="1080" alt="Screen Shot 2022-07-03 at 7 01 33 AM" src="https://user-images.githubusercontent.com/13699899/177043290-7172e823-6415-4c18-a99b-295a3f81fe7c.png">

In the duplicate manager, after cropping an image, the preview, is shown in a very small window even though it has not been cropped at all. In the screen shot the top image is the original, the bottom is the duplicate that has been cropped. The preview is the top image that is not cropped.

darktable version: 4.0.0
macOS Monterey 12.4

**Comment by paperdigits** [comment]
If this is a problem with darktable itself, you've reported it in the wrong repo. This repo is for docs.

If you're saying there is something wrong with the docs, it isn't clear me to what that is.

**Comment by BeagleDad** [comment]
Oops. My bad. I will move it.
