### ISSUE TITLE
Obscure explication for "delimiters for size categories" lighttable option

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/dtdocs#511]
> Size categories are used to allow different thumbnail overlays to be shown depending on the thumbnail size. A pipe delimited set of values defines at what image sizes the category changes. The default value of “120|400” means that there will be 3 categories of thumbnail: 0-120px, 120-400px and >400px.

I think that this text is obscure:
- only 2 values are allowed, or more?
- what does actually change when those thumbnail values are crossed? it's not explained

**Comment by paolobenve** [comment]
The following preference:

> **pattern for the thumbnail extended overlay text**

> If you have chosen to show extended overlay text over thumbnail images, this setting allows you to define what information is displayed. This pattern can use any of the variables defined in the [variables](https://docs.darktable.org/usermanual/4.0/en/special-topics/variables/) section.

It speaks of "chosen to show extended overlay text over thumbnail images". Nothing says where I choose to show this extended overlay text.

**Comment by elstoc** [comment]
Agreed this all needs explanation in the user manual. Thumbnail categories and overlays are all very complex and convoluted though, so probably needs a whole new section of the manual (though I think my preference would be rather to simplify the functionality).
