### ISSUE TITLE
Link to `stable` manual should redirect to `4.0` not `3.8`

### ISSUE THREAD

**Issue by navinsivakumar** [darktable-org/dtdocs#517]
My understanding is that `4.0` is the current stable version of darktable as of 2022-07-02. It looks like the default redirect for the manual currently still points to `3.8`. My understanding is that the link to the `stable` manual version should now redirect to `4.0`.

I'm not sure if this is the correct project to report this issue -- please let me know if there is a better place to file!

### Steps to reproduce
Navigate to https://docs.darktable.org/usermanual/stable/en

### Expected result
Redirect to https://docs.darktable.org/usermanual/4.0/en

### Actual result
Redirect to https://docs.darktable.org/usermanual/3.8/en

**Comment by elstoc** [comment]
I don't know how you even found this, since we don't use the stable url very much. But yes, it should point to the latest version.

@darix could you take a look please.

**Comment by darix** [comment]
done

**Comment by elstoc** [comment]
Thanks @darix

**Comment by navinsivakumar** [comment]
> I don't know how you even found this

I noticed it because some manual links from the darktable FAQ rely on the redirect (related to darktable-org/dtorg#200).
