### ISSUE TITLE
darktable 4.0 English HTML user manual has Chinese content

### ISSUE THREAD

**Issue by lphilpot** [darktable-org/dtdocs#519]
The online English HTML user manual at https://docs.darktable.org/usermanual/4.0/en/ includes content in Chinese. I assume that's not intentional.

It doesn't appear to affect the PDF but I didn't check the epub version. From a cursory scan it appears it's limited to these groups:

- Lighttable
- Darkroom
- Map
- Scripting with Lua
- Guides & tutorials
 
The text copy/paste below illustrates a sample:

```
Overview
Lighttable

    overview
    概述
    lighttable view layout
    映繪臺視角布局
    undo/redo
    取消/重做
    lighttable modes
    digital asset management

Darkroom

    overview
    概述
    darkroom view layout
    暗房視角布局
    the pixelpipe
    processing modules
    masking & blending
    organization
``` 

Thanks

**Comment by elstoc** [comment]
Hmm interesting. I have no earthly idea what's happened there.

**Comment by lphilpot** [comment]
This was in Firefox 104.0 on Windows 11 as well as Firefox and Chrome on Android 13, so it's not the browser.

**Comment by elstoc** [comment]
Yeah I think there's a new language been added to weblate but not reflected in the code. I'm running some tests.

**Comment by paperdigits** [comment]
I think it is Simplified Chinese.

**Comment by elstoc** [comment]
Fixed by adding it to the zh_Hant to the disabled languages list

**Comment by lphilpot** [comment]
Thank you!

*Len Philpot*
***@***.***
