### ISSUE TITLE
filmic rgb: contrast

### ISSUE THREAD

**Issue by kofa73** [darktable-org/dtdocs#520]
The meaning of contrast changed with [#10206.](https://github.com/darktable-org/darktable/pull/10206)
Is it still true that

> The larger the dynamic range, the greater the contrast should be set to, in order preserve a natural-looking image. 

https://github.com/darktable-org/dtdocs/blob/dc7f497dc9324bad07485a07abd7cd928589f005/content/module-reference/processing-modules/filmic-rgb.md?plain=1#L204

If not, suggested phrasing:

> The control sets the contrast (slope) around the mid-gray point, independent of the dynamic range. Note that if you adjust the white and black relative exposure controls, which define the dynamic range, the apparent slope of the curve will change, but that does not affect the contrast of midtones.

**Comment by elstoc** [comment]
What change are you suggesting here? This section still looks ok to me.

BTW it's really hard to view the text as you've entered it, since it displays on github as a single scrollable line so I've pasted the whole paragraph below as a quote:

> The contrast slider controls the slope of the middle part of the curve, as illustrated in the graph display. The larger the dynamic range, the greater the contrast should be set to, in order preserve a natural-looking image. This parameter mostly affects the mid-tones. Note that global contrast has an impact on the acutance (perceived sharpness) -- a low-contrast image will look unsharp even though it is optically sharp in the sense of the [Optical Transfer Function (OTF)](https://en.wikipedia.org/wiki/Optical_transfer_function).

**Comment by kofa73** [comment]
Thanks. I've added a suggestion.

I used a block-quote to highlight the part which may need adjustment.

**Comment by elstoc** [comment]
> Wasn't the requirement to increase contrast for higher dynamic range a side effect of dynamic range affecting midtone contrast? If yes, such an adjustment is no longer needed, is it?

I'm not sure. I got the impression that the main change was to ensure that the values of the sliders were no longer interdependent -- that prior to the change, adjusting black/white/hardness affected the slope. I'm not sure this affects any of the information/advice provided in the manual.

Perhaps @rawfiner or @aurelienpierre can advise.

**Comment by aurelienpierre** [comment]
I need to check. Low priority anyway.

**Comment by rawfiner** [comment]
> Wasn't the requirement to increase contrast for higher dynamic range a side effect of dynamic range affecting midtone contrast? If yes, such an adjustment is no longer needed, is it?

Indeed. I agree with you that it is no longer the case, and I agree with your suggested phrasing. However, note that the change of slope is only visible in "look only" view, so I am note sure if it is worth it to talk about it.

**Comment by kofa73** [comment]
_look only_ is the default view, I never switch to any of the others, in fact.
