### ISSUE TITLE
scene-referred module order - modules to add/remove

### ISSUE THREAD

**Issue by TiredOfGuessing** [darktable-org/dtdocs#528]
I believe the 4.0 manual “scene-referred module order” section needs a few updates based on the 4.0.1 app I have.

https://docs.darktable.org/usermanual/4.0/en/special-topics/module-order/

There is one addition, the blurs module is after censorize and before astrophoto denoise.

There are a number of modules no longer part of the SR module order.

35	color look up table
52	lut 3D
54	tone curve
62	color contrast
65	color zones
67	colorize
68	lowlight vision
71	soften
72	split-toning
76	dithering

**Comment by elstoc** [comment]
This section is a pain to maintain, and duplicates information that's already available within darktable's UI, so I've removed the section entirely within a52300d120
