### ISSUE TITLE
[RFC] Windows Support section in Special Topics

### ISSUE THREAD

**Issue by gi-man** [darktable-org/dtdocs#529]
Not for 4.2 since I wont have time to allow for translations, but maybe for 4.4

I've been thinking we should have a Special Topic section to deal with some of the tribal knowledge around windows. Some of the info is contained in the FAQ, like the location of folders, how to get to the log file, etc. 

I dont think it will be long, but it might help to have all the information in one section. Thoughts?

**Comment by elstoc** [comment]
I think this might be better on a web page on darktable.org or on a github wiki. The user manual is more about how the application itself is supposed to work and is supposed to be largely OS-agnostic.

**Comment by gi-man** [comment]
I will close this for now then. We had information in the FAQ already, but I feel it is in an obscure place instead of having it all in one place (a page in the manual). We point people to read the manual, but in the case of folder locations for windows they need to read the FAQ.
