### ISSUE TITLE
Rework on the highlights reconstruction module docs

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/dtdocs#538]
@elstoc i thought i had already sent this before but can't find it anymore. Anyway - @Iain and me did some work on documenting what hlr is about and how settings work.
*******************************

### Highlight reconstruction theory

Highlight reconstruction is a process for reducing the artefacts produced by clipping. Clipping is the loss of data when a digital number is too large for the bits required to store it. A similar problem occurs when an analogue system is overloaded. 
To understand highlight reconstruction we need to understand the initial steps of capturing and processing a digital image. 
In camera
Firstly, the sensor in your camera converts photons into an electrical charge. More photons mean more charge. Saturation occurs when a photosite(pixel) has reached the maximum amount of charge it can hold. Once this has happened, any additional photons hitting the sensor have no effect and information about how bright the pixel should be is lost. We know it should be brighter than the saturation point but we don’t know how much brighter.

Secondly, the electrical charges for each pixel are converted to a digital number. Ideally the saturation point of the sensor would be exactly the same as the digital clipping point to make use of the full digital range. However, often the saturation point is slightly below the digital clipping point to ensure the data from the sensor is not clipped at this stage. 

Some cameras even put the saturation point lower to ensure that sensor nonlinearities are not included in the data.

The digital value that represents the sensor saturation point is called the ‘white point’.

At the other end of the exposure range is the black point. This is the darkest level a sensor can accurately capture.

### Raw processor
Darktable then reads the data from the raw file and uses the ‘white point’ value to know which pixels have lost information due to saturation or clipping in camera. Darktable gives the black point a numerical value of zero and the white point the numerical value of one. If Darktable does not have the correct white point value, highlight reconstruction will not work as expected.

The next step is to apply ‘white balance’ to the image. Before applying white balance the clipped pixels for each colour channel are the same, so they will appear to be white. White balance scales each colour channel so that neutral grey/white colours in the scene appear neutral grey/white in your photo.

Typically, the red and blue channels are scaled up because your camera sensor is less sensitive to red and blue light. So now the red and blue channels have data above the clipping point of the green channel. This makes the highlights appear pink where the green channel is clipped.

If no channels are clipped, the colour of the highlights is correct.

The crude way to solve the problem of pink highlights is to clip the red and blue channels at the green channels clipping point, but this results in losing perfectly good data in the red and blue channels and creates other artefacts like shifts in hue and saturation.

### Highlight reconstruction
Highlight reconstruction is a way to avoid pink highlights or clipping good data by using data from unclipped channels to estimate the data in clipped channels.

### Highlight reconstruction methods
**Inpaint opposed**
This replaces ‘clip highlights’ as the default highlight reconstruction method since 4.2. 

This method restores clipped pixels by looking at selected pixels that are next to clipped regions and uses the average of all of these pixels to estimate the proper colour[1](https://github.com/darktable-org/dtdocs/issues/new#sdfootnote1sym) of the highlights. This works well for most images, but images that have clipped areas of significantly different colours may not work as well.

**Controls**
**Clip threshold.**
Pixels above this value are considered clipped. 

The mask button shows a false colour representation of the clipped pixels based on the clip threshold.

### Segmentation-based
**Introduction**

This highlight reconstruction method attempts to reconstruct clipped channels by estimating the “colour”1 of the clipped area by looking at the surrounding pixels. It works like this:

Each isolated clipped area is considered a segment. To estimate the colour of the segment, the pixels immediately surrounding the segment are analysed. One pixel unclipped will be selected to represent the colour of the clipped area. The colour ratios from the unclipped pixel are used to rebuild the clipped pixels in the segment.

Pixels that are too dark or look like an edge are rejected. If all pixels surrounding the segment are rejected the opposed inpainting method is used to recover that segment.

Segments that are close together are often the same object and can be combined so they are treated as one segment. 

Additionally, selecting segmentation based reconstruction allows rebuilding areas that have all channels clipped. It does this by estimating what might have been in the clipped area by looking at the surrounding gradients. 

It is best to consider this as a way to disguise fully clipped areas with something plausible, rather than a way to recover what was lost.  It should hopefully stop fully clipped areas from being distracting, not magically repair them.

**Controls**
**Clip threshold**.
Pixels above this value are considered clipped. This also adjusts the size of each segment. Lowering the threshold means more pixels are considered clipped so each segment grows. 

This algorithm is sensitive to the clip threshold because changing the size of the clipped segments changes which pixels are considered when determining the colour of the segment.

The clip threshold mask button shows a false colour representation of the clipped pixels based on the clip threshold.

### Combine
This is the radius at which close segments are considered part of the same larger segment. 

Sometimes separate clipped segments are part of the same object and it is best to combine them so that each segment does not get its own colour estimate. If they are not combined this can mean that each segment has a slightly different colour, even though they are the same object.

If nearby segments should have the same colour and don’t, increase the value of ‘_combine_’

The **combine mask button** shows the outline of clipped segments. If segments are combined then the outlines will be joined.

### Candidates
This controls the threshold for determining if each segment has a good candidate pixel. Segments without good candidates use the alternative method for estimating each segment's colour. 

The candidates mask button shows a false colour representation of the clipped segments which have good candidates, based on the setting of the slider. These will use segmentation-based highlight recovery. Segments not shown in the mask view fall back to the  ‘inpaint opposed’ method.

### Rebuild
This option rebuilds areas that have all channels clipped. The drop down menu provides several options. The 'mode' selected leads to a steeper or not-so-steep variant of rebuilding at the segment's borders The generic options adjusts the rebuilding to the size of the clipped area. The small and large options allow the user to override the automatic adjustment for size. 

The flat modes ignore very small/thin dark structures (like powerlines) in clipped segments to avoid artefacts.

When a rebuild option is selected the strength control adjusts how much effect the rebuilding has. The noise control allows the addition of some noise to make the rebuilt area more natural looking.

The rebuild mask button emphasises the rebuilt parts of the image.

### How to use Segmentation based highlight recovery

Turn off all modules except exposure, white balance, and highlight reconstruction. Set highlight reconstruction to ‘Segmentation-based HR’

Reduce exposure until the histogram shows there is no clipping

If the defaults results are unsatisfactory, then raise the clipping value until the highlights go a pinkish colour, then slowly and carefully lower the threshold until the highlights look better. 

If close segments have different colours then try raising ‘combine’.

If results are still poor then try adjusting ‘candidates’. For backlit scenes a low value of candidates is often the best. A low value means most or all of the clipped areas are being recovered with the ‘inpaint opposed’ algorithm.

Rebuilding fully clipped areas is a matter of trial-and-error. Start with generic and turn up the strength to see the result. Remember this is intended to disguise fully clipped areas, and stop them from being distracting, not as a magic fix.

If the area looks too smooth add some noise. Remember that Darktable also has a grain module, which may also help.

**Comment by elstoc** [comment]
Yeah thanks, you posted it [here](https://github.com/darktable-org/dtdocs/pull/534#issuecomment-1335548720) originally, I've just yet to get around to putting in a PR and copy-editing it (just busy with other things atm). It's not that complicated to update the docs (they're just markdown content) so if you could submit as a PR (and for your other issue too) that would be really helpful. Then I can merge the current version and edit later.

At first glance, I'd probably remove quite a lot of the initial "theory" section and replace it with the "how to use" section that's currently at the end.

**Comment by jenshannoschwalm** [comment]
I would propose to include some of the theory :-) there are so many misunderstandings around...

**Comment by elstoc** [comment]
I've tried to reduce this a little bit but I hope I've captured the essentials (https://github.com/darktable-org/dtdocs/pull/541)

**Comment by elstoc** [comment]
Resolved in #541
