### ISSUE TITLE
Documenting the "balanced OpenCL vs CPU tiling" option

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/dtdocs#539]
### Rationale
On many machines we find pretty fast multicore cpus and a lot of system ram but a significantly smaller gpu memory with somewhat resrticted number crunching power. There is no problem using OpenCL code in modules as long as that doesn't lead to excessive tiling with large overlapping areas. Such a situation was rare, now we have as examples D&S or laplacian highlights which might behave bad and it would have been better to use cpu code instead.
************

In DT 4.2 we have the CL device specific conf key expanded by an **advantage** value, it is set to zero by default.

### How does this work
While processing the pixelpipe we estimate overall workloads for both OpenCL and CPU (this is **not** static but depends on parameters set in the module thus defining tile size, number of tiles, tile overlap ...). In most cases we would prefer the OpenCL code to be executed even if that would mean tiling as the graphics cards is mostly much faster (often 10 times faster if it is a dedicated card).

If the ratio of estimated workloads (CPU vs GPU) is larger than the **advantage** hint, dt will use the CPU for processing that specific module this time.

Unfortunately there is no way to use some sort of benchmark so far, you have to find out the GPU advantage for your system yourself. 

### How to set up the advantage hint?

1. Measure performance (-d perf) in laplacian highlights after setting "diameter of reconstruction" to something high.
2. While doing so make sure (by -d tiling) that the cl code doesn't tile.
3. Check for execution times with opencl on and off.
4. The advantage option can now be set to approx (cpu-time / gpu-time)

**Comment by gi-man** [comment]
Complete when https://github.com/darktable-org/dtdocs/pull/542 is merged.
