### ISSUE TITLE
extended overlay text?

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/dtdocs#551]
https://docs.darktable.org/usermanual/4.2/en/preferences-settings/lighttable/ says:

> **pattern for the thumbnail extended overlay text**
> If you have chosen to show extended overlay text over thumbnail images, ...

Apparently, the manual doesn't says how I choose to show extended overlay text over thumbnail images...

Or maybe I cannot find it...?

**Comment by elstoc** [comment]
Yeah kinda the same response as to your issue from last year (https://github.com/darktable-org/dtdocs/issues/511). Needs a new section but it's really convoluted and hard to explain (we have a few pieces of functionality like this) so I never really know where to start.

**Comment by paolobenve** [comment]
If there isn't any option that actually decide whether to show or not extended overlay text over thumbnail images, I'd remove that phrase:

from

"If you have chosen to show extended overlay text over thumbnail images, this setting allows etc."

to

"This setting allows etc."

**Comment by elstoc** [comment]
There is an option - click the star button in the lighttable view to see it

**Comment by paolobenve** [comment]
I can't find it...

**Comment by elstoc** [comment]
![Screenshot_2023-01-26_19-40-27](https://user-images.githubusercontent.com/9555491/214933910-2e4d11b4-639f-4ae0-881f-67ecb8d8e53b.png)

**Comment by paolobenve** [comment]
> Size categories are used to allow different thumbnail overlays to be shown depending on the thumbnail size. A pipe delimited set of values defines at what image sizes the category changes. The default value of “120|400” means that there will be 3 categories of thumbnail: 0-120px, 120-400px and >400px.

could change to

> Size categories are used to allow different thumbnail overlays to be shown depending on the thumbnail size. A pipe delimited set of values defines at what image sizes the category changes. The default value of “120|400” means that there will be 3 categories of thumbnail: 0-120px, 120-400px and >400px. Clicking the top star in lighttable view permits to decide which overlays has to be used for the thumbnail size that is currently used.

And

> If you have chosen to show extended overlay text over thumbnail images,

to

> If you have chosen (clicking the top star in lighttable view) to show extended overlay text over thumbnail images,

Adding the star icon into the two texts would surely help the user to find it in the UI
