### ISSUE TITLE
missing IMAGE.EXIF variable

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/dtdocs#552]
in https://docs.darktable.org/usermanual/4.2/en/special-topics/variables/ the IMAGE.EXIF variable is not listed.

It appears in src/common/variables.c

**Comment by victoryforce** [comment]
@paolobenve This variable was even removed at one point, but was later restored just for backwards compatibility. But it is not returned to the displayed completion list. This is done specifically to not suggest this variable for use. So it would be logical not to document it. It is kept for compatibility, but is deprecated. See https://github.com/darktable-org/darktable/pull/11251 for details.

@elstoc I suggest closing this issue.

**Comment by elstoc** [comment]
Makes sense to me
