### ISSUE TITLE
G

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/dtdocs#557]
https://github.com/darktable-org/darktable/commit/ecd66a0e07e876de949615fc03cb6cd84dbfc826

**Comment by elstoc** [comment]
G? I think this might need some more info

**Comment by elstoc** [comment]
Seriously, though, I see nothing on that link that tells me what the purpose of this issue is. Please add some info or close it.

**Comment by jenshannoschwalm** [comment]
Sorry, i didn't even recognize i opend it
