### ISSUE TITLE
darktable user manual/4.2.1/sigmoid

### ISSUE THREAD

**Issue by zakfm** [darktable-org/dtdocs#559]
Hello, Here is my contribution for the French manual with the translation of the paragraph for sigmoid. Thank you.
[Sigmoid.pdf](https://github.com/darktable-org/dtdocs/files/11069465/Sigmoid.pdf)

**Comment by elstoc** [comment]
Translations of the user manual are done via our [weblate](https://weblate.pixls.us/projects/darktable/dtdocs/) instance and should be applied there. Unfortunately we are unable to accept translations through the dtdocs repository.

You should be aware, though, that the English manual is still not complete for the 4.2 release so you'll have to wait for weblate to be updated with the sigmoid documentation before you can translate it.
