### ISSUE TITLE
User manual for all version / format on dtorg is empty

### ISSUE THREAD

**Issue by kanru** [darktable-org/dtdocs#575]
Hi, this might be broken recently. As of now, all the manuals on https://www.darktable.org/resources/ is empty.

html:

![Screenshot from 2023-06-11 07-14-57](https://github.com/darktable-org/dtdocs/assets/17571/feb5d407-3197-439b-bff1-6fe9934f4b73)

pdf:

![Screenshot from 2023-06-11 07-15-53](https://github.com/darktable-org/dtdocs/assets/17571/0cdac747-3722-42f6-8bec-467c0c19b85f)

**Comment by elstoc** [comment]
Yes we're aware of this. It's being investigated.

**Comment by ssmendon** [comment]
It seems to build fine if you follow the README to build the HTML documentation with Hugo. Does the issue have something to do with your deployment environment?

**Comment by paperdigits** [comment]
Yes, we have a container with all the bits we need, but something is wrong there and I haven't figured out what that is.

**Comment by ssmendon** [comment]
@paperdigits how does the deployment of the document site work, at a high-level? Is the [gh-pages.yaml](.github/workflows/gh-pages.yaml) the flow for it, or is there a different container?

**Comment by paperdigits** [comment]
There is a different container, and a script that runs every so often, builds everything...

I can reproduce the issue locally with the container, so its difficult.

**Comment by elstoc** [comment]
This should be fixed now
