### ISSUE TITLE
PDF of version 4.4

### ISSUE THREAD

**Issue by diefau** [darktable-org/dtdocs#576]
I downloaded https://docs.darktable.org/usermanual/4.4/en/darktable_user_manual.pdf.
Firefox 102 shows it well but neither evince nor atril nor okular can show it.
They show only "Unable to open document. PDF document is damaged".
(All programs under Debian sid).

**Comment by paperdigits** [comment]
It renders fine for me on the latest Firefox mobile and v114 on my desktop.

Firefox 102 is pretty far out of date.

I'm not sure what to tell you, but it doesn't seem to be broken.

**Comment by diefau** [comment]
Normally I use atril to read PDFs (offline), which can't show the user-manual 4.4.

**Comment by paperdigits** [comment]
ah, I see the issue. working on a fix

**Comment by paperdigits** [comment]
Works for me in Okular now, thanks for the report.

**Comment by diefau** [comment]
Now it works for me too (with all the three readers).
Thank you very much!!!
Can you tell, what the problem was?
