### ISSUE TITLE
https://darktable-org.github.io/dtdocs/en/darktable_user_manual.pdf is empty

### ISSUE THREAD

**Issue by kanyck** [darktable-org/dtdocs#579]
Cannot get a local version of new manual: https://darktable-org.github.io/dtdocs/en/darktable_user_manual.pdf is empty,
darktable.org doesn't open anymore as well as pixls.us, though.

**Comment by paperdigits** [comment]
The pixls server disk crashed. We are working to get it restored.

We don't build the PDF for the master branch, so you'll need to wait for pixls to come back, make due with the HTML, or clone the docs repo install the tools then you can make your own PDF.

**Comment by kanyck** [comment]
So I'll wait, thanks for the clarification! But in this case I think the link should be removed or directed to the latest release.

**Comment by elstoc** [comment]
The pdf should work but something is wrong with the build process. Hopefully you'll be able to get it off the main darktable.org site once it's back up

**Comment by kanyck** [comment]
Still 404...

**Comment by paperdigits** [comment]
looks like its working to me.
