### ISSUE TITLE
Module fusion Tone curve and RGB Curve

### ISSUE THREAD

**Issue by ActarusLeGrand** [darktable-org/dtdocs#580]
As both do the same thing except one is Lab the other RGB, why not put both on the same and have a toggle switch for RBG to Lab?

**Comment by elstoc** [comment]
I think it's confusing for us to document two modules as if they were one module. Or did you mean to raise a feature request for darktable? You should raise these on the [darktable repository](https://github.com/darktable-org/darktable/issues)
