### ISSUE TITLE
mask manager - masks ordered bottom-to-top as of 4.4

### ISSUE THREAD

**Issue by TiredOfGuessing** [darktable-org/dtdocs#589]
I believe this was changed from the original (from top to bottom) to bottom-to-top based on a request by Boris Hajdukovic. 

Excerpted...
Masks are constructed by adding a group of shapes to the image in the order that they are listed **(from top to bottom).**

[https://docs.darktable.org/usermanual/development/en/module-reference/utility-modules/darkroom/mask-manager/#masks--groups](url)

**Comment by paperdigits** [comment]
Can you cite a PR on the darktable repo and please submit a PR with the necessary changes?

**Comment by TiredOfGuessing** [comment]
Sorry, I don't know enough to answer (pull request) you are requesting. I need to learn more about GitHub terminology and processes. 

The code changes have already been made and are in v4.4.2. Here are the GitHub requests I found.

Mask manager: Change the order (hierarchy) of shapes in group from bottom to top #14154
[https://github.com/darktable-org/darktable/issues/14154](url)

RFC: Masks manager: Change order (hierarchy) of shapes #14405
[https://github.com/darktable-org/darktable/pull/14405](url)

This looks like the corresponding commit?
[https://github.com/darktable-org/darktable/pull/14405/commits/46495ea1ad8229e814c7413c9bf31481fe907a83](url)

My 4.4.2 install clearly orders mask from bottom (oldest) to top (newest) as shown in the attached screen capture. Both group exposure-2 is above group exposure-1 and brush#3 is above brush#2.
![maskmgr_Screenshot2023-10-26](https://github.com/darktable-org/dtdocs/assets/105315850/4bcac1c2-7f45-4dbf-91e4-c7d34aabae29)

**Comment by elstoc** [comment]
This is resolved now
