### ISSUE TITLE
Move all 'deprecated' modules to the end of the modules listing

### ISSUE THREAD

**Issue by scrste** [darktable-org/dtdocs#606]
For a new user a major challenge is to get some handle on the very large number of modules contained in Darktable. In the user manual, this list is made even longer by leaving deprecated modules within the alphabetically ordered active modules list. 

I propose that deprecated module information be grouped together at the end of the modules listing to enable new users to ignore deprecated modules while long-time users who need to be aware of newly deprecated modules can conveniently check an aggregated list to quickly assess changes they need to make in their own work.

**Comment by elstoc** [comment]
Yeah that's not a bad idea. I suspect we can do it by adding weights to the front-matter.
