### ISSUE TITLE
Install damage error for Darktable on Mac 

### ISSUE THREAD

**Issue by krattster** [darktable-org/dtdocs#621]
Hi,

I have tried to install Darktable on my Macbook Pro (M3 Max on Mac OS 14.2.1). After downloading and trying to install an error message appears that suggests the Darktable file is damaged. I have repeated a number of times with no success. Wondering what I can do to fix and install Darktable. Thank you for your assistance. I have attached screen shots to help clarify.

<img width="299" alt="Screenshot 2024-02-04 at 8 39 04 pm" src="https://github.com/darktable-org/dtdocs/assets/158797971/879c231c-e40e-41a3-a0da-e83d373ba770">
<img width="746" alt="Screenshot 2024-02-04 at 8 39 19 pm" src="https://github.com/darktable-org/dtdocs/assets/158797971/2873b36d-f39d-48d6-af08-09d2603a10a1">
<img width="304" alt="Screenshot 2024-02-04 at 8 39 31 pm" src="https://github.com/darktable-org/dtdocs/assets/158797971/7f99d3af-e419-4274-8053-cec27bf3b4f8">
<img width="554" alt="Screenshot 2024-02-04 at 8 39 45 pm" src="https://github.com/darktable-org/dtdocs/assets/158797971/94359846-aed3-4515-a842-b23ece939e41">
<img width="352" alt="Screenshot 2024-02-04 at 8 40 27 pm" src="https://github.com/darktable-org/dtdocs/assets/158797971/58a1cfac-6a7e-4052-bd6b-1e4ac124372b">

**Comment by elstoc** [comment]
This repository is for the darktable _documentation_. You should raise issues with the darktable _application_ [here](https://github.com/darktable-org/darktable/issues).
