### ISSUE TITLE
Translation of DT 4.6 into French

### ISSUE THREAD

**Issue by Christian-Bouhon** [darktable-org/dtdocs#635]
Hello,
FYI, the translation of the DT 4.6 user manual has been finalized in Weblate: https://weblate.pixls.us/projects/darktable/dtdocs/fr/ .
What is the procedure for publishing the manual? The text does not appear on https://docs.darktable.org/usermanual/4.6/en/ .
Greetings from Brussels,
Christian

**Comment by paperdigits** [comment]
It has to be integrated, it is a manual process done by Chris or myself, it is not automatic.

**Comment by elstoc** [comment]
Thanks for letting us know. This will get updated the next time we push translations to the repo
