### ISSUE TITLE
Text improvements to curves.md

### ISSUE THREAD

**Issue by alikstimix** [darktable-org/dtdocs#656]
Note this is a learning exercise for me: I'm fully aware this isn't the largest priority for the manual!

in curves.md in the last 3 paragraphs, the words abscissa and ordinate are used.  These are positively Victorian terms which will likely mystify the vast majority of the audience.  

Much better to use: "x and y axes" and also clarify that the scale changes from linear to log-log when you change the 'scale for graph ' sliders o the 2 penultimate paras would read:

: By default, a “linear” scale is used (defined by a scale factor of 0). This scale uses evenly spaced **x and y** [[replacing *abscissa and ordinates*]] axes.

: **The 'scale for graph' slider sets ** logarithmic scales **which** will compress the high values and dilate the low values, on both the **x and y axes** [[replacing *abscissa and the axis of ordinates]*], so that the nodes in lowlights get more space on the graph and can be controlled more clearly.

**Comment by elstoc** [comment]
"horizontal" and "vertical" are better than "x" and "y"

**Comment by alikstimix** [comment]
Sounds like a style guide issue.  I have noticed quite a few mentions of x and y axis in the current manual text, do you want get a standard usage of horix/vert? or just propose a change whenever I come across "x" s and "y" s

**Comment by elstoc** [comment]
Up to you. I think if we're trying to cater for people who have forgotten their high school maths, horizontal/vertical is generally better but I don't feel the need to be 100% consistent on this. I know there are sections that necessarily get much more mathsy/sciency than "x y coordinates" but generally the simpler we can make the language the better for everyone.

**Comment by alikstimix** [comment]
OK understood, if its just talk about a graph then horiz/vert; if its maths/science then x and y is better (speaking as an ex mathematician) so i the curves section talking about log-log graphs I think x and y should be used.

**Comment by elstoc** [comment]
Not exactly what I was saying. More that we should reduce the maths-speak unless it's absolutely necessary. If we can use simpler terms we should do so. I know adults who still forget which axis is x and which is y.
