### ISSUE TITLE
Latest PDF manual shows wrong Darktable version

### ISSUE THREAD

**Issue by adrianlopezroche** [darktable-org/dtdocs#678]
The link to the PDF manual on the [Darktable 4.8 user manual page](https://docs.darktable.org/usermanual/4.8/en/) reads 4.6 as the version number when it should be 4.8. This includes both the title page and the footer. Also, the [resources](https://www.darktable.org/resources/) page needs to be updated to include a link to the Darktable 4.8 user manuals.

**Comment by elstoc** [comment]
Thanks for reminding me to do some work on it though, I might take a look at it again this weekend.
