### ISSUE TITLE
Disable MIDI feature

### ISSUE THREAD

**Issue by johansmolinski** [darktable-org/dtdocs#684]
Is there a way to completely disable the MIDI features of darktable? I have lots of controllers connected as I use my computer for music too, but it makes no sense to control darktable with MPE keyboards or breath controllers.

Using macOS, I get tons of unassigned messages, and I believe those are the reason for the program to run extremely slow and barely responds to inputs.

**Comment by elstoc** [comment]
You should raise this on the [darktable repository](https://github.com/darktable-org/darktable/issues). This is for documentation (user manual) changes.
