### ISSUE TITLE
Various typos in the pot file

### ISSUE THREAD

**Issue by JeanLucCoulon** [darktable-org/dtdocs#692]
Hi,
I've found several typos in the pot file.
I've regenerated it before editing (generate-translations.sh --no-translations).

Please find attached the suggested modifications.
[content.pot.partial.txt](https://github.com/user-attachments/files/18083235/content.pot.partial.txt)

Format of the file:
##########
# FaultySpelling -> CorrectedSpelling
#
# references
<msgid>

Regards
Jean-Luc

**Comment by elstoc** [comment]
Fixed in ea701738c28a816b0a9bc1745e4ced50017e434e. We don't do direct updates to the pot file but will manually regenerate it from the content at some point.
