### ISSUE TITLE
Update documentation for Exposure Adjustment in Scopes module

### ISSUE THREAD

**Issue by tpinfold** [darktable-org/dtdocs#694]
Be gentle, this is my first attempt at trying to contribute towards updating documentation in darktable. I would appreciate advice on how I can do this in the best fashion. I have reviewed Exposure histogram proxy #17838 and see documentation is needed. I have written an updated version of the relevant section of the documentation using Word. 
[Exposure histogram.docx](https://github.com/user-attachments/files/18157968/Exposure.histogram.docx)

**Comment by elstoc** [comment]
It's usually easier for us to directly see what you've changed and be able to post our own edits -- a pull request is usually the best way to do this. If you can't face learning how to do this locally with the git command line, you can also do at least an initial edit directly in the github web interface.

Simply go to the relevant file in this repository (start [here](https://github.com/darktable-org/dtdocs/tree/master/content) and then navigate through the sections as you would the website to locate the file you want to change). Click the "Edit" button and make your changes and when you're done click the "commit" button and select "Create a branch and start a pull request".

**Comment by tpinfold** [comment]
I have taken @elstoc advice and posted the pull request as suggested so I will close this request. Thanks for your guidance Chris.

**Comment by elstoc** [comment]
@tpinfold I don't see your pull request

**Comment by tpinfold** [comment]
@elstoc I am not sure what I did wrong. I followed all the steps and created a branch, I may or may not have created a pull request, but now when I follow your supplied link I go to scopes and only see png files. here is my screen shot. I am keen to help out if I can master the system. 

<img width="472" alt="image" src="https://github.com/user-attachments/assets/dd1c6ace-fad7-4340-b36d-55e1e3048a30" />

**Comment by elstoc** [comment]
The markdown file is one directory back from that (in `shared/scopes.md`)

**Comment by tpinfold** [comment]
@elstoc I have hopefully created a PR correctly now. Thanks for your help.

**Comment by elstoc** [comment]
Nope, still no PR in this repository. It would be listed [here](https://github.com/darktable-org/dtdocs/pulls)

**Comment by tpinfold** [comment]
What an I doing wrong? Thanks for your help. 
https://github.com/darktable-org/dtdocs/compare/master...tpinfold:patch-2?expand=1

**Comment by elstoc** [comment]
What happens when you click the green button at the bottom?

**Comment by tpinfold** [comment]
Hopefully the PR has gone through now. Thanks
