### ISSUE TITLE
Allow previous/next links to move between sections as well as within them

### ISSUE THREAD

**Issue by elstoc** [darktable-org/dtdocs#82]
Previous/next links on the bottom of pages currently start and end in the current section. For example `overview/sidecar-files/sidecar` should (but doesn't) contain a 'previous' link to the section header `overview/sidecar-files` and `overview/sidecar-files/local-copies` should (but doesn't) contain a 'next' link to `overview/workflow`.

I think @paperdigits and @patdavid are already working on a solution for this.

**Comment by elstoc** [comment]
Ok I've found a fix but I'm not sure how to push stuff to gitlab and it can probably be done more neatly anyway so I'll summarise it here and provide some files.

1. Add a new partial `themes/hugo-darktable-docs-theme/layouts/partials/getprevnext.html` (renamed to txt so I can attach it). 

   This iterates through the pages (in much the same way as the nav does) and puts the previous and next links and titles into page scratch variables.

   [getprevnext.txt](https://github.com/darktable-org/dtdocs/files/5602283/getprevnext.txt)

2. Amend `themes/hugo-darktable-docs-theme/layouts/_default/baseof.html` to call the new partial

   [baseof.txt](https://github.com/darktable-org/dtdocs/files/5602323/baseof.txt)

3. Amend `themes/hugo-darktable-docs-theme/layouts/partials/prev-next.html` to use the new variables

   [prev-next.txt](https://github.com/darktable-org/dtdocs/files/5602320/prev-next.txt)

**Comment by elstoc** [comment]
I think the current layout of the manual (in terms of breadcrumbs and prev/next links) is quite nice and worth retaining. With this fix and the breadcrumbs we can probably do so. 

i.e. on the top of the page:

![Screenshot_2020-11-26_11-03-18](https://user-images.githubusercontent.com/9555491/100343297-157e3980-2fd7-11eb-90aa-8e9332fb0196.png)

and at the bottom:

![Screenshot_2020-11-26_11-03-38](https://user-images.githubusercontent.com/9555491/100343324-20d16500-2fd7-11eb-94c9-1ea37cb33487.png)

**Comment by johnny-bit** [comment]
IMO that looks perfect and retains all functionality of ye olde in-tree xmldoc manual.

**Comment by paperdigits** [comment]
Fixed in 2d10e074e3ac48e04beb6a1bfe2346a52ac25467

Kudos @elstoc
