### ISSUE TITLE
agree and formalise shortcut style standards

### ISSUE THREAD

**Issue by elstoc** [darktable-org/dtdocs#85]
Style standards for keyboard and mouse actions aren't entirely consistent at the moment.

For example, keyboard shortcuts are generally defined using fixed width with letters in capitals (e.g. `Ctrl+R`) but mouse clicks aren't very consistently referenced. My opinion is that standalone mouse actions should all be plain text because they often form a part of sentences and things like "`Click` on the button to..." at the start of a sentence seem odd. Similarly when using "right click" or "middle click" or "scroll". When using keyboard and mouse combinations it might be better to put the whole thing in fixed-width, so "`Ctrl+click`" rather than "`Ctrl`+click".

**Comment by elstoc** [comment]
TBH I think the only thing that looks reasonable and consistent is to have the entire shortcut as plaintext regardless of whether it contains key or mouse actions. All letter keys should be upper case and function or modifier keys should have an initial capital letter. So scroll, click, double-click, Enter, Shift+click, Ctrl, Ctrl+scroll, M, Ctrl+M.

**Comment by matt-maguire** [comment]
I think it comes down to whether it is a verb or a noun/adjective. Therefore, click and drag on the image to select a region; you select the region using a `Click+Drag` (operation).

**Comment by elstoc** [comment]
Again though I'd much prefer to represent all of these with plaintext rather than as "code" (fixed width). On balance I would prefer to say "click and drag to select a region" rather than "select using a Click+Drag" which sounds slightly clumsy wording.

**Comment by elstoc** [comment]
Resolved
